const reserved = [
    [["epub"], "application/epub+zip"],
    [["sdp"], "application/sdp"],
    [["zip"], "application/zip"],
    [["exr"], "image/aces"],
    [["apng"], "image/apng"],
    [["avif"], "image/avif"],
    [["bmp"], "image/bmp"],
    [["cgm"], "image/cgm"],
    [["drle"], "image/dicom-rle"],
    [["emf"], "image/emf"],
    [["fits"], "image/fits"],
    [["g3"], "image/g3fax"],
    [["gif"], "image/gif"],
    [["heic"], "image/heic"],
    [["heics"], "image/heic-sequence"],
    [["heif"], "image/heif"],
    [["heifs"], "image/heif-sequence"],
    [["hej2"], "image/hej2k"],
    [["hsj2"], "image/hsj2"],
    [["ief"], "image/ief"],
    [["jls"], "image/jls"],
    [["jp2", "jpg2"], "image/jp2"],
    [["jpeg", "jpg", "jpe"], "image/jpeg"],
    [["jph"], "image/jph"],
    [["jhc"], "image/jphc"],
    [["jpm"], "image/jpm"],
    [["jpx", "jpf"], "image/jpx"],
    [["jxr"], "image/jxr"],
    [["jxra"], "image/jxra"],
    [["jxrs"], "image/jxrs"],
    [["jxs"], "image/jxs"],
    [["jxsc"], "image/jxsc"],
    [["jxsi"], "image/jxsi"],
    [["jxss"], "image/jxss"],
    [["ktx"], "image/ktx"],
    [["ktx2"], "image/ktx2"],
    [["png"], "image/png"],
    [["sgi"], "image/sgi"],
    [["svg", "svgz"], "image/svg+xml"],
    [["t38"], "image/t38"],
    [["tif", "tiff"], "image/tiff"],
    [["tfx"], "image/tiff-fx"],
    [["webp"], "image/webp"],
    [["wmf"], "image/wmf"],
    [["psd"], "image/vnd.adobe.photoshop"],
    [["azv"], "image/vnd.airzip.accelerator.azv"],
    [["uvi", "uvvi", "uvg", "uvvg"], "image/vnd.dece.graphic"],
    [["djvu", "djv"], "image/vnd.djvu"],
    [["*sub"], "image/vnd.dvb.subtitle"],
    [["dwg"], "image/vnd.dwg"],
    [["dxf"], "image/vnd.dxf"],
    [["fbs"], "image/vnd.fastbidsheet"],
    [["fpx"], "image/vnd.fpx"],
    [["fst"], "image/vnd.fst"],
    [["mmr"], "image/vnd.fujixerox.edmics-mmr"],
    [["rlc"], "image/vnd.fujixerox.edmics-rlc"],
    [["ico"], "image/vnd.microsoft.icon"],
    [["dds"], "image/vnd.ms-dds"],
    [["mdi"], "image/vnd.ms-modi"],
    [["wdp"], "image/vnd.ms-photo"],
    [["npx"], "image/vnd.net-fpx"],
    [["b16"], "image/vnd.pco.b16"],
    [["tap"], "image/vnd.tencent.tap"],
    [["vtf"], "image/vnd.valve.source.texture"],
    [["wbmp"], "image/vnd.wap.wbmp"],
    [["xif"], "image/vnd.xiff"],
    [["pcx"], "image/vnd.zbrush.pcx"],
    [["3ds"], "image/x-3ds"],
    [["ras"], "image/x-cmu-raster"],
    [["cmx"], "image/x-cmx"],
    [["fh", "fhc", "fh4", "fh5", "fh7"], "image/x-freehand"],
    [["*ico"], "image/x-icon"],
    [["jng"], "image/x-jng"],
    [["sid"], "image/x-mrsid-image"],
    [["*bmp"], "image/x-ms-bmp"],
    [["*pcx"], "image/x-pcx"],
    [["pic", "pct"], "image/x-pict"],
    [["pnm"], "image/x-portable-anymap"],
    [["pbm"], "image/x-portable-bitmap"],
    [["pgm"], "image/x-portable-graymap"],
    [["ppm"], "image/x-portable-pixmap"],
    [["rgb"], "image/x-rgb"],
    [["tga"], "image/x-tga"],
    [["xbm"], "image/x-xbitmap"],
    [["xpm"], "image/x-xpixmap"],
    [["xwd"], "image/x-xwindowdump"],
    [["txt", "text", "conf", "def", "list", "log", "in", "ini"], "text/plain"],
].reduce((obj, [keys, value]) => {
    for (const key of keys) {
        Object.defineProperty(obj, key, { value })
    }
    return obj
}, {});
let mime = new Proxy(reserved, { get: (target, ext) => target.hasOwnProperty(ext) ? target[ext] : '' });