
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa={},g;for(g in d)d.hasOwnProperty(g)&&(aa[g]=d[g]);var ba="./this.program";function ca(a,b){throw b;}var da=!1,u=!1,w=!1,ea=!1;da="object"===typeof window;u="function"===typeof importScripts;w="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!da&&!w&&!u;var z="",A,fa,ha,ia;
if(w)z=u?require("path").dirname(z)+"/":__dirname+"/",A=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},fa=function(a){a=A(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",B),ca=function(a){process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};
else if(ea)"undefined"!=typeof read&&(A=function(a){return read(a)}),fa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(ca=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||u)u?z=self.location.href:document.currentScript&&(z=document.currentScript.src),
_scriptDir&&(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=d.print||console.log.bind(console),E=d.printErr||console.warn.bind(console);for(g in aa)aa.hasOwnProperty(g)&&(d[g]=aa[g]);aa=null;d.thisProgram&&(ba=d.thisProgram);
d.quit&&(ca=d.quit);var la;d.wasmBinary&&(la=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&E("no native wasm support detected");var F,ma=new WebAssembly.Table({initial:1549,maximum:1549,element:"anyfunc"}),na=!1;function assert(a,b){a||B("Assertion failed: "+b)}function oa(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function pa(a,b,c,e){var f={string:function(n){var r=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;r=qa(t);ra(n,G,r,t)}return r},array:function(n){var r=qa(n.length);H.set(n,r);return r}},h=oa(a),l=[];a=0;if(e)for(var m=0;m<e.length;m++){var p=f[c[m]];p?(0===a&&(a=sa()),l[m]=p(e[m])):l[m]=e[m]}c=h.apply(null,l);c=function(n){return"string"===b?I(n):"boolean"===b?!!n:n}(c);0!==a&&ta(a);return c}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function J(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|l:(f&7)<<18|h<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function I(a){return a?J(G,a,void 0):""}
function ra(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var m=a.charCodeAt(++h);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function va(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a){var b;for(b=a>>1;K[b];)++b;b<<=1;if(32<b-a&&wa)return wa.decode(G.subarray(a,b));b=0;for(var c="";;){var e=K[a+2*b>>1];if(0==e)return c;++b;c+=String.fromCharCode(e)}}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)K[b>>1]=a.charCodeAt(f),b+=2;K[b>>1]=0;return b-e}function Aa(a){return 2*a.length}function Ba(a){for(var b=0,c="";;){var e=L[a+4*b>>2];if(0==e)return c;++b;65536<=e?(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023)):c+=String.fromCharCode(e)}}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}L[b>>2]=h;b+=4;if(b+4>c)break}L[b>>2]=0;return b-e}function Da(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var Ea,H,G,K,Fa,L,M,Ga,Ha;
function Ia(a){Ea=a;d.HEAP8=H=new Int8Array(a);d.HEAP16=K=new Int16Array(a);d.HEAP32=L=new Int32Array(a);d.HEAPU8=G=new Uint8Array(a);d.HEAPU16=Fa=new Uint16Array(a);d.HEAPU32=M=new Uint32Array(a);d.HEAPF32=Ga=new Float32Array(a);d.HEAPF64=Ha=new Float64Array(a)}var Ja=d.INITIAL_MEMORY||16777216;d.wasmMemory?F=d.wasmMemory:F=new WebAssembly.Memory({initial:Ja/65536,maximum:32768});F&&(Ea=F.buffer);Ja=Ea.byteLength;Ia(Ea);L[53948]=5458832;
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Rc;"number"===typeof c?void 0===b.Kb?d.dynCall_v(c):d.dynCall_vi(c,b.Kb):c(void 0===b.Kb?null:b.Kb)}}}var La=[],Ma=[],Na=[],Oa=[];function Pa(){var a=d.preRun.shift();La.unshift(a)}var Qa=Math.abs,Ra=Math.ceil,Sa=Math.floor,Ta=Math.min,N=0,Ua=null,Va=null;function Wa(){N++;d.monitorRunDependencies&&d.monitorRunDependencies(N)}
function Xa(){N--;d.monitorRunDependencies&&d.monitorRunDependencies(N);if(0==N&&(null!==Ua&&(clearInterval(Ua),Ua=null),Va)){var a=Va;Va=null;a()}}d.preloadedImages={};d.preloadedAudios={};function B(a){if(d.onAbort)d.onAbort(a);ka(a);E(a);na=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ya(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Za(){return Ya("data:application/octet-stream;base64,")}
var O="../wasm/plugin.wasm";if(!Za()){var $a=O;O=d.locateFile?d.locateFile($a,z):z+$a}function ab(){try{if(la)return new Uint8Array(la);if(fa)return fa(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function bb(){return la||!da&&!u||"function"!==typeof fetch||Ya("file://")?new Promise(function(a){a(ab())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return ab()})}
var cb,db;Ma.push({Rc:function(){eb()}});function fb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function gb(){return 0<gb.Wa}function hb(a){return L[ib()>>2]=a}function jb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function kb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=jb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function lb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function P(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function mb(){var a=Array.prototype.slice.call(arguments,0);return kb(a.join("/"))}function Q(a,b){return kb(a+"/"+b)}function R(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:S.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=jb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function nb(a,b){function c(l){for(var m=0;m<l.length&&""===l[m];m++);for(var p=l.length-1;0<=p&&""===l[p];p--);return m>p?[]:l.slice(m,p-m+1)}a=R(a).substr(1);b=R(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,h=0;h<e;h++)if(a[h]!==b[h]){f=h;break}e=[];for(h=f;h<a.length;h++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var ob=[];function pb(a,b){ob[a]={input:[],output:[],ob:b};S.$b(a,qb)}
var qb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new S.Ka(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ob.flush(a.tty)},flush:function(a){a.tty.ob.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ob.nc)throw new S.Ka(60);for(var f=0,h=0;h<e;h++){try{var l=a.tty.ob.nc(a.tty)}catch(m){throw new S.Ka(29);}if(void 0===l&&0===f)throw new S.Ka(6);if(null===l||void 0===l)break;f++;b[c+h]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.ob.Wb)throw new S.Ka(60);
try{for(var f=0;f<e;f++)a.tty.ob.Wb(a.tty,b[c+f])}catch(h){throw new S.Ka(29);}e&&(a.node.timestamp=Date.now());return f}},sb={nc:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.Wa?Buffer.Wa(256):new Buffer(256),e=0;try{e=ha.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=rb(b,!0)}return a.input.shift()},Wb:function(a,b){null===b||10===b?(ka(J(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(J(a.output,0)),a.output=[])}},tb={Wb:function(a,b){null===b||10===b?(E(J(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(E(J(a.output,0)),a.output=[])}},T={ab:null,Qa:function(){return T.createNode(null,
"/",16895,0)},createNode:function(a,b,c,e){if(S.Uc(c)||S.isFIFO(c))throw new S.Ka(63);T.ab||(T.ab={dir:{node:{Ya:T.Ma.Ya,Ta:T.Ma.Ta,lookup:T.Ma.lookup,fb:T.Ma.fb,rename:T.Ma.rename,unlink:T.Ma.unlink,rmdir:T.Ma.rmdir,readdir:T.Ma.readdir,symlink:T.Ma.symlink},stream:{Za:T.Na.Za}},file:{node:{Ya:T.Ma.Ya,Ta:T.Ma.Ta},stream:{Za:T.Na.Za,read:T.Na.read,write:T.Na.write,rb:T.Na.rb,vb:T.Na.vb,nb:T.Na.nb}},link:{node:{Ya:T.Ma.Ya,Ta:T.Ma.Ta,readlink:T.Ma.readlink},stream:{}},dc:{node:{Ya:T.Ma.Ya,Ta:T.Ma.Ta},
stream:S.Hc}});c=S.createNode(a,b,c,e);S.Sa(c.mode)?(c.Ma=T.ab.dir.node,c.Na=T.ab.dir.stream,c.La={}):S.isFile(c.mode)?(c.Ma=T.ab.file.node,c.Na=T.ab.file.stream,c.Oa=0,c.La=null):S.ub(c.mode)?(c.Ma=T.ab.link.node,c.Na=T.ab.link.stream):S.Ab(c.mode)&&(c.Ma=T.ab.dc.node,c.Na=T.ab.dc.stream);c.timestamp=Date.now();a&&(a.La[b]=c);return c},wd:function(a){if(a.La&&a.La.subarray){for(var b=[],c=0;c<a.Oa;++c)b.push(a.La[c]);return b}return a.La},xd:function(a){return a.La?a.La.subarray?a.La.subarray(0,
a.Oa):new Uint8Array(a.La):new Uint8Array(0)},jc:function(a,b){var c=a.La?a.La.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Oa&&a.La.set(c.subarray(0,a.Oa),0))},dd:function(a,b){if(a.Oa!=b)if(0==b)a.La=null,a.Oa=0;else{if(!a.La||a.La.subarray){var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,a.Oa)))}else if(a.La||(a.La=[]),a.La.length>b)a.La.length=b;else for(;a.La.length<b;)a.La.push(0);a.Oa=b}},Ma:{Ya:function(a){var b=
{};b.dev=S.Ab(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;S.Sa(a.mode)?b.size=4096:S.isFile(a.mode)?b.size=a.Oa:S.ub(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Fc=4096;b.blocks=Math.ceil(b.size/b.Fc);return b},Ta:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.dd(a,b.size)},lookup:function(){throw S.Nb[44];},fb:function(a,
b,c,e){return T.createNode(a,b,c,e)},rename:function(a,b,c){if(S.Sa(a.mode)){try{var e=S.eb(b,c)}catch(h){}if(e)for(var f in e.La)throw new S.Ka(55);}delete a.parent.La[a.name];a.name=c;b.La[c]=a;a.parent=b},unlink:function(a,b){delete a.La[b]},rmdir:function(a,b){var c=S.eb(a,b),e;for(e in c.La)throw new S.Ka(55);delete a.La[b]},readdir:function(a){var b=[".",".."],c;for(c in a.La)a.La.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!S.ub(a.mode))throw new S.Ka(28);
return a.link}},Na:{read:function(a,b,c,e,f){var h=a.node.La;if(f>=a.node.Oa)return 0;a=Math.min(a.node.Oa-f,e);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=h[f+e];return a},write:function(a,b,c,e,f,h){b.buffer===H.buffer&&(h=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(h)return a.La=b.subarray(c,c+e),a.Oa=e;if(0===a.Oa&&0===f)return a.La=b.slice(c,c+e),a.Oa=e;if(f+e<=a.Oa)return a.La.set(b.subarray(c,c+e),f),e}T.jc(a,f+
e);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,c+e),f);else for(h=0;h<e;h++)a.La[f+h]=b[c+h];a.Oa=Math.max(a.Oa,f+e);return e},Za:function(a,b,c){1===c?b+=a.position:2===c&&S.isFile(a.node.mode)&&(b+=a.node.Oa);if(0>b)throw new S.Ka(28);return b},rb:function(a,b,c){T.jc(a.node,b+c);a.node.Oa=Math.max(a.node.Oa,b+c)},vb:function(a,b,c,e,f,h,l){if(!S.isFile(a.node.mode))throw new S.Ka(43);a=a.node.La;if(l&2||a.buffer!==b.buffer){if(0<f||f+e<a.length)a.subarray?a=a.subarray(f,f+e):a=Array.prototype.slice.call(a,
f,f+e);f=!0;l=b.buffer==H.buffer;e=ub(e);if(!e)throw new S.Ka(48);(l?H:b).set(a,e)}else f=!1,e=a.byteOffset;return{Kd:e,Dc:f}},nb:function(a,b,c,e,f){if(!S.isFile(a.node.mode))throw new S.Ka(43);if(f&2)return 0;T.Na.write(a,b,0,e,c,!1);return 0}}},S={root:null,xb:[],hc:{},streams:[],Zc:1,$a:null,fc:"/",Qb:!1,rc:!0,Ra:{},vc:{tc:{zc:1,Ac:2}},Ka:null,Nb:{},Pc:null,Eb:0,yd:function(a){if(!(a instanceof S.Ka)){a:{var b=Error();if(!b.stack){try{throw Error();}catch(c){b=c}if(!b.stack){b="(no stack trace available)";
break a}}b=b.stack.toString()}d.extraStackTrace&&(b+="\n"+d.extraStackTrace());b=fb(b);throw a+" : "+b;}return hb(a.Va)},Pa:function(a,b){a=R(S.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Mb:!0,Yb:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.Yb)throw new S.Ka(32);a=jb(a.split("/").filter(function(l){return!!l}),!1);var f=S.root;c="/";for(e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;f=S.eb(f,a[e]);c=Q(c,a[e]);S.ib(f)&&(!h||h&&b.Mb)&&(f=f.wb.root);if(!h||b.Xa)for(h=
0;S.ub(f.mode);)if(f=S.readlink(c),c=R(lb(c),f),f=S.Pa(c,{Yb:b.Yb}).node,40<h++)throw new S.Ka(32);}return{path:c,node:f}},cb:function(a){for(var b;;){if(S.Bb(a))return a=a.Qa.sc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Pb:function(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%S.$a.length},pc:function(a){var b=S.Pb(a.parent.id,a.name);a.kb=S.$a[b];S.$a[b]=a},qc:function(a){var b=S.Pb(a.parent.id,a.name);if(S.$a[b]===a)S.$a[b]=a.kb;
else for(b=S.$a[b];b;){if(b.kb===a){b.kb=a.kb;break}b=b.kb}},eb:function(a,b){var c=S.Wc(a);if(c)throw new S.Ka(c,a);for(c=S.$a[S.Pb(a.id,b)];c;c=c.kb){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return S.lookup(a,b)},createNode:function(a,b,c,e){a=new S.wc(a,b,c,e);S.pc(a);return a},Lb:function(a){S.qc(a)},Bb:function(a){return a===a.parent},ib:function(a){return!!a.wb},isFile:function(a){return 32768===(a&61440)},Sa:function(a){return 16384===(a&61440)},ub:function(a){return 40960===(a&61440)},
Ab:function(a){return 8192===(a&61440)},Uc:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Qc:{r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218},Yc:function(a){var b=S.Qc[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},kc:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},lb:function(a,b){if(S.rc)return 0;
if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0},Wc:function(a){var b=S.lb(a,"x");return b?b:a.Ma.lookup?0:2},Vb:function(a,b){try{return S.eb(a,b),20}catch(c){}return S.lb(a,"wx")},Cb:function(a,b,c){try{var e=S.eb(a,b)}catch(f){return f.Va}if(a=S.lb(a,"wx"))return a;if(c){if(!S.Sa(e.mode))return 54;if(S.Bb(e)||S.cb(e)===S.cwd())return 10}else if(S.Sa(e.mode))return 31;return 0},Xc:function(a,b){return a?
S.ub(a.mode)?32:S.Sa(a.mode)&&("r"!==S.kc(b)||b&512)?31:S.lb(a,S.kc(b)):44},yc:4096,$c:function(a,b){b=b||S.yc;for(a=a||0;a<=b;a++)if(!S.streams[a])return a;throw new S.Ka(33);},mb:function(a){return S.streams[a]},Oc:function(a,b,c){S.Ib||(S.Ib=function(){},S.Ib.prototype={object:{get:function(){return this.node},set:function(h){this.node=h}}});var e=new S.Ib,f;for(f in a)e[f]=a[f];a=e;b=S.$c(b,c);a.fd=b;return S.streams[b]=a},Ic:function(a){S.streams[a]=null},Hc:{open:function(a){a.Na=S.Sc(a.node.rdev).Na;
a.Na.open&&a.Na.open(a)},Za:function(){throw new S.Ka(70);}},Ub:function(a){return a>>8},Ed:function(a){return a&255},jb:function(a,b){return a<<8|b},$b:function(a,b){S.hc[a]={Na:b}},Sc:function(a){return S.hc[a]},mc:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.xb)}return b},uc:function(a,b){function c(l){S.Eb--;return b(l)}function e(l){if(l){if(!e.Wa)return e.Wa=!0,c(l)}else++h>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);S.Eb++;1<S.Eb&&E("warning: "+
S.Eb+" FS.syncfs operations in flight at once, probably just doing extra work");var f=S.mc(S.root.Qa),h=0;f.forEach(function(l){if(!l.type.uc)return e(null);l.type.uc(l,a,e)})},Qa:function(a,b,c){var e="/"===c,f=!c;if(e&&S.root)throw new S.Ka(10);if(!e&&!f){var h=S.Pa(c,{Mb:!1});c=h.path;h=h.node;if(S.ib(h))throw new S.Ka(10);if(!S.Sa(h.mode))throw new S.Ka(54);}b={type:a,Id:b,sc:c,xb:[]};a=a.Qa(b);a.Qa=b;b.root=a;e?S.root=a:h&&(h.wb=b,h.Qa&&h.Qa.xb.push(b));return a},Od:function(a){a=S.Pa(a,{Mb:!1});
if(!S.ib(a.node))throw new S.Ka(28);a=a.node;var b=a.wb,c=S.mc(b);Object.keys(S.$a).forEach(function(e){for(e=S.$a[e];e;){var f=e.kb;-1!==c.indexOf(e.Qa)&&S.Lb(e);e=f}});a.wb=null;a.Qa.xb.splice(a.Qa.xb.indexOf(b),1)},lookup:function(a,b){return a.Ma.lookup(a,b)},fb:function(a,b,c){var e=S.Pa(a,{parent:!0}).node;a=P(a);if(!a||"."===a||".."===a)throw new S.Ka(28);var f=S.Vb(e,a);if(f)throw new S.Ka(f);if(!e.Ma.fb)throw new S.Ka(63);return e.Ma.fb(e,a,b,c)},create:function(a,b){return S.fb(a,(void 0!==
b?b:438)&4095|32768,0)},mkdir:function(a,b){return S.fb(a,(void 0!==b?b:511)&1023|16384,0)},Fd:function(a,b){a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{S.mkdir(c,b)}catch(f){if(20!=f.Va)throw f;}}},Db:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return S.fb(a,b|8192,c)},symlink:function(a,b){if(!R(a))throw new S.Ka(44);var c=S.Pa(b,{parent:!0}).node;if(!c)throw new S.Ka(44);b=P(b);var e=S.Vb(c,b);if(e)throw new S.Ka(e);if(!c.Ma.symlink)throw new S.Ka(63);return c.Ma.symlink(c,
b,a)},rename:function(a,b){var c=lb(a),e=lb(b),f=P(a),h=P(b);try{var l=S.Pa(a,{parent:!0});var m=l.node;l=S.Pa(b,{parent:!0});var p=l.node}catch(r){throw new S.Ka(10);}if(!m||!p)throw new S.Ka(44);if(m.Qa!==p.Qa)throw new S.Ka(75);l=S.eb(m,f);e=nb(a,e);if("."!==e.charAt(0))throw new S.Ka(28);e=nb(b,c);if("."!==e.charAt(0))throw new S.Ka(55);try{var n=S.eb(p,h)}catch(r){}if(l!==n){c=S.Sa(l.mode);if(f=S.Cb(m,f,c))throw new S.Ka(f);if(f=n?S.Cb(p,h,c):S.Vb(p,h))throw new S.Ka(f);if(!m.Ma.rename)throw new S.Ka(63);
if(S.ib(l)||n&&S.ib(n))throw new S.Ka(10);if(p!==m&&(f=S.lb(m,"w")))throw new S.Ka(f);try{S.Ra.willMovePath&&S.Ra.willMovePath(a,b)}catch(r){E("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}S.qc(l);try{m.Ma.rename(l,p,h)}catch(r){throw r;}finally{S.pc(l)}try{if(S.Ra.onMovePath)S.Ra.onMovePath(a,b)}catch(r){E("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=S.Pa(a,{parent:!0}).node,c=P(a),e=S.eb(b,
c),f=S.Cb(b,c,!0);if(f)throw new S.Ka(f);if(!b.Ma.rmdir)throw new S.Ka(63);if(S.ib(e))throw new S.Ka(10);try{S.Ra.willDeletePath&&S.Ra.willDeletePath(a)}catch(h){E("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ma.rmdir(b,c);S.Lb(e);try{if(S.Ra.onDeletePath)S.Ra.onDeletePath(a)}catch(h){E("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readdir:function(a){a=S.Pa(a,{Xa:!0}).node;if(!a.Ma.readdir)throw new S.Ka(54);return a.Ma.readdir(a)},
unlink:function(a){var b=S.Pa(a,{parent:!0}).node,c=P(a),e=S.eb(b,c),f=S.Cb(b,c,!1);if(f)throw new S.Ka(f);if(!b.Ma.unlink)throw new S.Ka(63);if(S.ib(e))throw new S.Ka(10);try{S.Ra.willDeletePath&&S.Ra.willDeletePath(a)}catch(h){E("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ma.unlink(b,c);S.Lb(e);try{if(S.Ra.onDeletePath)S.Ra.onDeletePath(a)}catch(h){E("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readlink:function(a){a=S.Pa(a).node;
if(!a)throw new S.Ka(44);if(!a.Ma.readlink)throw new S.Ka(28);return R(S.cb(a.parent),a.Ma.readlink(a))},stat:function(a,b){a=S.Pa(a,{Xa:!b}).node;if(!a)throw new S.Ka(44);if(!a.Ma.Ya)throw new S.Ka(63);return a.Ma.Ya(a)},lstat:function(a){return S.stat(a,!0)},chmod:function(a,b,c){var e;"string"===typeof a?e=S.Pa(a,{Xa:!c}).node:e=a;if(!e.Ma.Ta)throw new S.Ka(63);e.Ma.Ta(e,{mode:b&4095|e.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){S.chmod(a,b,!0)},fchmod:function(a,b){a=S.mb(a);if(!a)throw new S.Ka(8);
S.chmod(a.node,b)},chown:function(a,b,c,e){var f;"string"===typeof a?f=S.Pa(a,{Xa:!e}).node:f=a;if(!f.Ma.Ta)throw new S.Ka(63);f.Ma.Ta(f,{timestamp:Date.now()})},lchown:function(a,b,c){S.chown(a,b,c,!0)},fchown:function(a,b,c){a=S.mb(a);if(!a)throw new S.Ka(8);S.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new S.Ka(28);var c;"string"===typeof a?c=S.Pa(a,{Xa:!0}).node:c=a;if(!c.Ma.Ta)throw new S.Ka(63);if(S.Sa(c.mode))throw new S.Ka(31);if(!S.isFile(c.mode))throw new S.Ka(28);if(a=S.lb(c,
"w"))throw new S.Ka(a);c.Ma.Ta(c,{size:b,timestamp:Date.now()})},vd:function(a,b){a=S.mb(a);if(!a)throw new S.Ka(8);if(0===(a.flags&2097155))throw new S.Ka(28);S.truncate(a.node,b)},Pd:function(a,b,c){a=S.Pa(a,{Xa:!0}).node;a.Ma.Ta(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,e,f){if(""===a)throw new S.Ka(44);b="string"===typeof b?S.Yc(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=kb(a);try{h=S.Pa(a,{Xa:!(b&131072)}).node}catch(m){}}var l=!1;if(b&
64)if(h){if(b&128)throw new S.Ka(20);}else h=S.fb(a,c,0),l=!0;if(!h)throw new S.Ka(44);S.Ab(h.mode)&&(b&=-513);if(b&65536&&!S.Sa(h.mode))throw new S.Ka(54);if(!l&&(c=S.Xc(h,b)))throw new S.Ka(c);b&512&&S.truncate(h,0);b&=-131713;e=S.Oc({node:h,path:S.cb(h),flags:b,seekable:!0,position:0,Na:h.Na,md:[],error:!1},e,f);e.Na.open&&e.Na.open(e);!d.logReadFiles||b&1||(S.Xb||(S.Xb={}),a in S.Xb||(S.Xb[a]=1,E("FS.trackingDelegate error on read file: "+a)));try{S.Ra.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=S.vc.tc.zc),
0!==(b&2097155)&&(f|=S.vc.tc.Ac),S.Ra.onOpenFile(a,f))}catch(m){E("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return e},close:function(a){if(S.tb(a))throw new S.Ka(8);a.Ob&&(a.Ob=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{S.Ic(a.fd)}a.fd=null},tb:function(a){return null===a.fd},Za:function(a,b,c){if(S.tb(a))throw new S.Ka(8);if(!a.seekable||!a.Na.Za)throw new S.Ka(70);if(0!=c&&1!=c&&2!=c)throw new S.Ka(28);a.position=a.Na.Za(a,b,c);a.md=[];
return a.position},read:function(a,b,c,e,f){if(0>e||0>f)throw new S.Ka(28);if(S.tb(a))throw new S.Ka(8);if(1===(a.flags&2097155))throw new S.Ka(8);if(S.Sa(a.node.mode))throw new S.Ka(31);if(!a.Na.read)throw new S.Ka(28);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new S.Ka(70);b=a.Na.read(a,b,c,e,f);h||(a.position+=b);return b},write:function(a,b,c,e,f,h){if(0>e||0>f)throw new S.Ka(28);if(S.tb(a))throw new S.Ka(8);if(0===(a.flags&2097155))throw new S.Ka(8);if(S.Sa(a.node.mode))throw new S.Ka(31);
if(!a.Na.write)throw new S.Ka(28);a.seekable&&a.flags&1024&&S.Za(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new S.Ka(70);b=a.Na.write(a,b,c,e,f,h);l||(a.position+=b);try{if(a.path&&S.Ra.onWriteToFile)S.Ra.onWriteToFile(a.path)}catch(m){E("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},rb:function(a,b,c){if(S.tb(a))throw new S.Ka(8);if(0>b||0>=c)throw new S.Ka(28);if(0===(a.flags&2097155))throw new S.Ka(8);if(!S.isFile(a.node.mode)&&
!S.Sa(a.node.mode))throw new S.Ka(43);if(!a.Na.rb)throw new S.Ka(138);a.Na.rb(a,b,c)},vb:function(a,b,c,e,f,h,l){if(0!==(h&2)&&0===(l&2)&&2!==(a.flags&2097155))throw new S.Ka(2);if(1===(a.flags&2097155))throw new S.Ka(2);if(!a.Na.vb)throw new S.Ka(43);return a.Na.vb(a,b,c,e,f,h,l)},nb:function(a,b,c,e,f){return a&&a.Na.nb?a.Na.nb(a,b,c,e,f):0},Gd:function(){return 0},Rb:function(a,b,c){if(!a.Na.Rb)throw new S.Ka(59);return a.Na.Rb(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||"r";b.encoding=
b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=S.open(a,b.flags);a=S.stat(a).size;var f=new Uint8Array(a);S.read(e,f,0,a,0);"utf8"===b.encoding?c=J(f,0):"binary"===b.encoding&&(c=f);S.close(e);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||"w";a=S.open(a,c.flags,c.mode);if("string"===typeof b){var e=new Uint8Array(va(b)+1);b=ra(b,e,0,e.length);S.write(a,e,0,b,void 0,c.Gc)}else if(ArrayBuffer.isView(b))S.write(a,
b,0,b.byteLength,void 0,c.Gc);else throw Error("Unsupported data type");S.close(a)},cwd:function(){return S.fc},chdir:function(a){a=S.Pa(a,{Xa:!0});if(null===a.node)throw new S.Ka(44);if(!S.Sa(a.node.mode))throw new S.Ka(54);var b=S.lb(a.node,"x");if(b)throw new S.Ka(b);S.fc=a.path},Kc:function(){S.mkdir("/tmp");S.mkdir("/home");S.mkdir("/home/web_user")},Jc:function(){S.mkdir("/dev");S.$b(S.jb(1,3),{read:function(){return 0},write:function(e,f,h,l){return l}});S.Db("/dev/null",S.jb(1,3));pb(S.jb(5,
0),sb);pb(S.jb(6,0),tb);S.Db("/dev/tty",S.jb(5,0));S.Db("/dev/tty1",S.jb(6,0));if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(w)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(e){}b||(b=function(){B("random_device")});S.gb("/dev","random",b);S.gb("/dev","urandom",b);S.mkdir("/dev/shm");S.mkdir("/dev/shm/tmp")},Mc:function(){S.mkdir("/proc");S.mkdir("/proc/self");
S.mkdir("/proc/self/fd");S.Qa({Qa:function(){var a=S.createNode("/proc/self","fd",16895,73);a.Ma={lookup:function(b,c){var e=S.mb(+c);if(!e)throw new S.Ka(8);b={parent:null,Qa:{sc:"fake"},Ma:{readlink:function(){return e.path}}};return b.parent=b}};return a}},{},"/proc/self/fd")},Nc:function(){d.stdin?S.gb("/dev","stdin",d.stdin):S.symlink("/dev/tty","/dev/stdin");d.stdout?S.gb("/dev","stdout",null,d.stdout):S.symlink("/dev/tty","/dev/stdout");d.stderr?S.gb("/dev","stderr",null,d.stderr):S.symlink("/dev/tty1",
"/dev/stderr");S.open("/dev/stdin","r");S.open("/dev/stdout","w");S.open("/dev/stderr","w")},ic:function(){S.Ka||(S.Ka=function(a,b){this.node=b;this.ed=function(c){this.Va=c};this.ed(a);this.message="FS error"},S.Ka.prototype=Error(),S.Ka.prototype.constructor=S.Ka,[44].forEach(function(a){S.Nb[a]=new S.Ka(a);S.Nb[a].stack="<generic error, no stack>"}))},gd:function(){S.ic();S.$a=Array(4096);S.Qa(T,{},"/");S.Kc();S.Jc();S.Mc();S.Pc={MEMFS:T}},sb:function(a,b,c){S.sb.Qb=!0;S.ic();d.stdin=a||d.stdin;
d.stdout=b||d.stdout;d.stderr=c||d.stderr;S.Nc()},quit:function(){S.sb.Qb=!1;var a=d._fflush;a&&a(0);for(a=0;a<S.streams.length;a++){var b=S.streams[a];b&&S.close(b)}},zb:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Ad:function(a,b){a=mb.apply(null,a);b&&"/"==a[0]&&(a=a.substr(1));return a},nd:function(a,b){return R(b,a)},Md:function(a){return kb(a)},ud:function(a,b){a=S.Jb(a,b);if(a.exists)return a.object;hb(a.error);return null},Jb:function(a,b){try{var c=S.Pa(a,{Xa:!b});a=c.path}catch(f){}var e=
{Bb:!1,exists:!1,error:0,name:null,path:null,object:null,ad:!1,cd:null,bd:null};try{c=S.Pa(a,{parent:!0}),e.ad=!0,e.cd=c.path,e.bd=c.node,e.name=P(a),c=S.Pa(a,{Xa:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.Bb="/"===c.path}catch(f){e.error=f.Va}return e},pd:function(a,b,c,e){a=Q("string"===typeof a?a:S.cb(a),b);return S.mkdir(a,S.zb(c,e))},sd:function(a,b){a="string"===typeof a?a:S.cb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=Q(a,c);try{S.mkdir(e)}catch(f){}a=
e}}return e},Lc:function(a,b,c,e,f){a=Q("string"===typeof a?a:S.cb(a),b);return S.create(a,S.zb(e,f))},ec:function(a,b,c,e,f,h){a=b?Q("string"===typeof a?a:S.cb(a),b):a;e=S.zb(e,f);f=S.create(a,e);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}S.chmod(f,e|146);a=S.open(f,"w");S.write(a,c,0,c.length,0,h);S.close(a);S.chmod(f,e)}return f},gb:function(a,b,c,e){a=Q("string"===typeof a?a:S.cb(a),b);b=S.zb(!!c,!!e);S.gb.Ub||(S.gb.Ub=64);var f=S.jb(S.gb.Ub++,
0);S.$b(f,{open:function(h){h.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(h,l,m,p){for(var n=0,r=0;r<p;r++){try{var t=c()}catch(x){throw new S.Ka(29);}if(void 0===t&&0===n)throw new S.Ka(6);if(null===t||void 0===t)break;n++;l[m+r]=t}n&&(h.node.timestamp=Date.now());return n},write:function(h,l,m,p){for(var n=0;n<p;n++)try{e(l[m+n])}catch(r){throw new S.Ka(29);}p&&(h.node.timestamp=Date.now());return n}});return S.Db(a,b,f)},rd:function(a,b,c){a=Q("string"===typeof a?
a:S.cb(a),b);return S.symlink(c,a)},lc:function(a){if(a.Sb||a.Vc||a.link||a.La)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(A)try{a.La=rb(A(a.url),!0),a.Oa=a.La.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||hb(29);return b},qd:function(a,
b,c,e,f){function h(){this.Tb=!1;this.Wa=[]}h.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.chunkSize;return this.oc(n/this.chunkSize|0)[r]}};h.prototype.xc=function(n){this.oc=n};h.prototype.cc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),t,x=(t=n.getResponseHeader("Accept-Ranges"))&&"bytes"===t;n=
(t=n.getResponseHeader("Content-Encoding"))&&"gzip"===t;var k=1048576;x||(k=r);var q=this;q.xc(function(v){var y=v*k,C=(v+1)*k-1;C=Math.min(C,r-1);if("undefined"===typeof q.Wa[v]){var ya=q.Wa;if(y>C)throw Error("invalid range ("+y+", "+C+") or no bytes requested!");if(C>r-1)throw Error("only "+r+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);r!==k&&D.setRequestHeader("Range","bytes="+y+"-"+C);"undefined"!=typeof Uint8Array&&(D.responseType="arraybuffer");D.overrideMimeType&&
D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);y=void 0!==D.response?new Uint8Array(D.response||[]):rb(D.responseText||"",!0);ya[v]=y}if("undefined"===typeof q.Wa[v])throw Error("doXHR failed!");return q.Wa[v]});if(n||!r)k=r=1,k=r=this.oc(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.Cc=r;this.Bc=k;this.Tb=!0};if("undefined"!==
typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new h;Object.defineProperties(l,{length:{get:function(){this.Tb||this.cc();return this.Cc}},chunkSize:{get:function(){this.Tb||this.cc();return this.Bc}}});l={Sb:!1,La:l}}else l={Sb:!1,url:c};var m=S.Lc(a,b,l,e,f);l.La?m.La=l.La:l.url&&(m.La=null,m.url=l.url);Object.defineProperties(m,{Oa:{get:function(){return this.La.length}}});var p={};Object.keys(m.Na).forEach(function(n){var r=
m.Na[n];p[n]=function(){if(!S.lc(m))throw new S.Ka(29);return r.apply(null,arguments)}});p.read=function(n,r,t,x,k){if(!S.lc(m))throw new S.Ka(29);n=n.node.La;if(k>=n.length)return 0;x=Math.min(n.length-k,x);if(n.slice)for(var q=0;q<x;q++)r[t+q]=n[k+q];else for(q=0;q<x;q++)r[t+q]=n.get(k+q);return x};m.Na=p;return m},td:function(a,b,c,e,f,h,l,m,p,n){function r(x){function k(v){n&&n();m||S.ec(a,b,v,e,f,p);h&&h();Xa()}var q=!1;d.preloadPlugins.forEach(function(v){!q&&v.canHandle(t)&&(v.handle(x,t,k,
function(){l&&l();Xa()}),q=!0)});q||k(x)}vb.sb();var t=b?R(Q(a,b)):a;Wa();"string"==typeof c?vb.od(c,function(x){r(x)},l):r(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},ac:function(){return"EM_FS_"+window.location.pathname},bc:20,qb:"FILE_DATA",Ld:function(a,b,c){b=b||function(){};c=c||function(){};var e=S.indexedDB();try{var f=e.open(S.ac(),S.bc)}catch(h){return c(h)}f.onupgradeneeded=function(){ka("creating db");f.result.createObjectStore(S.qb)};
f.onsuccess=function(){var h=f.result.transaction([S.qb],"readwrite"),l=h.objectStore(S.qb),m=0,p=0,n=a.length;a.forEach(function(r){r=l.put(S.Jb(r).object.La,r);r.onsuccess=function(){m++;m+p==n&&(0==p?b():c())};r.onerror=function(){p++;m+p==n&&(0==p?b():c())}});h.onerror=c};f.onerror=c},Cd:function(a,b,c){b=b||function(){};c=c||function(){};var e=S.indexedDB();try{var f=e.open(S.ac(),S.bc)}catch(h){return c(h)}f.onupgradeneeded=c;f.onsuccess=function(){var h=f.result;try{var l=h.transaction([S.qb],
"readonly")}catch(t){c(t);return}var m=l.objectStore(S.qb),p=0,n=0,r=a.length;a.forEach(function(t){var x=m.get(t);x.onsuccess=function(){S.Jb(t).exists&&S.unlink(t);S.ec(lb(t),P(t),x.result,!0,!0,!0);p++;p+n==r&&(0==n?b():c())};x.onerror=function(){n++;p+n==r&&(0==n?b():c())}});l.onerror=c};f.onerror=c}},wb={},xb=void 0;function yb(){xb+=4;return L[xb-4>>2]}function zb(a){a=S.mb(a);if(!a)throw new S.Ka(8);return a}
function Ab(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Bb=void 0;function U(a){for(var b="";G[a];)b+=Bb[G[a++]];return b}var Cb={},V={},Db={};function Eb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Fb(a,b){a=Eb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Gb(a){var b=Error,c=Fb(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Hb=void 0;function W(a){throw new Hb(a);}var Ib=void 0;function Jb(a,b){function c(m){m=b(m);if(m.length!==e.length)throw new Ib("Mismatched type converter count");for(var p=0;p<e.length;++p)X(e[p],m[p])}var e=[];e.forEach(function(m){Db[m]=a});var f=Array(a.length),h=[],l=0;a.forEach(function(m,p){V.hasOwnProperty(m)?f[p]=V[m]:(h.push(m),Cb.hasOwnProperty(m)||(Cb[m]=[]),Cb[m].push(function(){f[p]=V[m];++l;l===h.length&&c(f)}))});0===h.length&&c(f)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||W('type "'+e+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.Tc)return;W("Cannot register type '"+e+"' twice")}V[a]=b;delete Db[a];Cb.hasOwnProperty(a)&&(b=Cb[a],delete Cb[a],b.forEach(function(f){f()}))}var Kb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Lb(a){4<a&&0===--Y[a].Zb&&(Y[a]=void 0,Kb.push(a))}function Mb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Kb.length?Kb.pop():Y.length;Y[b]={Zb:1,value:a};return b}}function Nb(a){return this.fromWireType(M[a>>2])}function Ob(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Pb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ga[c>>2])};case 3:return function(c){return this.fromWireType(Ha[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Qb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Fb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Rb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Sb(a,b){var c=d;if(void 0===c[a].bb){var e=c[a];c[a]=function(){c[a].bb.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].bb+")!");return c[a].bb[arguments.length].apply(this,arguments)};c[a].bb=[];c[a].bb[e.Ec]=e}}
function Tb(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].bb&&void 0!==d[a].bb[c])&&W("Cannot register public name '"+a+"' twice"),Sb(a,a),d.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].bb[c]=b):(d[a]=b,void 0!==c&&(d[a].Hd=c))}function Ub(a,b){for(var c=[],e=0;e<a;e++)c.push(L[(b>>2)+e]);return c}
function Vb(a,b){a=U(a);var c=d["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var Wb=void 0;function Xb(a){a=Yb(a);var b=U(a);Z(a);return b}
function Zb(a,b){function c(h){f[h]||V[h]||(Db[h]?Db[h].forEach(c):(e.push(h),f[h]=!0))}var e=[],f={};b.forEach(c);throw new Wb(a+": "+e.map(Xb).join([", "]));}function $b(a,b,c){switch(b){case 0:return c?function(e){return H[e]}:function(e){return G[e]};case 1:return c?function(e){return K[e>>1]}:function(e){return Fa[e>>1]};case 2:return c?function(e){return L[e>>2]}:function(e){return M[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var ac;
w?ac=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ac=dateNow:ac=function(){return performance.now()};var bc={};function cc(){if(!dc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in bc)a[b]=bc[b];var c=[];for(b in a)c.push(b+"="+a[b]);dc=c}return dc}var dc;
function ec(a){return 0===a%4&&(0!==a%100||0===a%400)}function fc(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var hc=[31,29,31,30,31,30,31,31,30,31,30,31],ic=[31,28,31,30,31,30,31,31,30,31,30,31];function jc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(ec(a.getFullYear())?hc:ic)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function kc(a,b,c,e){function f(k,q,v){for(k="number"===typeof k?k.toString():k||"";k.length<q;)k=v[0]+k;return k}function h(k,q){return f(k,q,"0")}function l(k,q){function v(C){return 0>C?-1:0<C?1:0}var y;0===(y=v(k.getFullYear()-q.getFullYear()))&&0===(y=v(k.getMonth()-q.getMonth()))&&(y=v(k.getDate()-q.getDate()));return y}function m(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function p(k){k=jc(new Date(k.Ua+1900,0,1),k.Hb);var q=new Date(k.getFullYear()+1,0,4),v=m(new Date(k.getFullYear(),0,4));q=m(q);return 0>=l(v,k)?0>=l(q,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=L[e+40>>2];e={kd:L[e>>2],jd:L[e+4>>2],Fb:L[e+8>>2],yb:L[e+12>>2],pb:L[e+16>>2],Ua:L[e+20>>2],Gb:L[e+24>>2],Hb:L[e+28>>2],Nd:L[e+32>>2],hd:L[e+
36>>2],ld:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return t[k.Gb].substring(0,3)},"%A":function(k){return t[k.Gb]},"%b":function(k){return x[k.pb].substring(0,3)},"%B":function(k){return x[k.pb]},"%C":function(k){return h((k.Ua+1900)/100|0,2)},"%d":function(k){return h(k.yb,2)},"%e":function(k){return f(k.yb,2," ")},"%g":function(k){return p(k).toString().substring(2)},"%G":function(k){return p(k)},"%H":function(k){return h(k.Fb,
2)},"%I":function(k){k=k.Fb;0==k?k=12:12<k&&(k-=12);return h(k,2)},"%j":function(k){return h(k.yb+fc(ec(k.Ua+1900)?hc:ic,k.pb-1),3)},"%m":function(k){return h(k.pb+1,2)},"%M":function(k){return h(k.jd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Fb&&12>k.Fb?"AM":"PM"},"%S":function(k){return h(k.kd,2)},"%t":function(){return"\t"},"%u":function(k){return k.Gb||7},"%U":function(k){var q=new Date(k.Ua+1900,0,1),v=0===q.getDay()?q:jc(q,7-q.getDay());k=new Date(k.Ua+1900,k.pb,k.yb);return 0>
l(v,k)?h(Math.ceil((31-v.getDate()+(fc(ec(k.getFullYear())?hc:ic,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(v,q)?"01":"00"},"%V":function(k){var q=new Date(k.Ua+1901,0,4),v=m(new Date(k.Ua+1900,0,4));q=m(q);var y=jc(new Date(k.Ua+1900,0,1),k.Hb);return 0>l(y,v)?"53":0>=l(q,y)?"01":h(Math.ceil((v.getFullYear()<k.Ua+1900?k.Hb+32-v.getDate():k.Hb+1-v.getDate())/7),2)},"%w":function(k){return k.Gb},"%W":function(k){var q=new Date(k.Ua,0,1),v=1===q.getDay()?q:jc(q,0===q.getDay()?1:7-q.getDay()+1);k=
new Date(k.Ua+1900,k.pb,k.yb);return 0>l(v,k)?h(Math.ceil((31-v.getDate()+(fc(ec(k.getFullYear())?hc:ic,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(v,q)?"01":"00"},"%y":function(k){return(k.Ua+1900).toString().substring(2)},"%Y":function(k){return k.Ua+1900},"%z":function(k){k=k.hd;var q=0<=k;k=Math.abs(k)/60;return(q?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.ld},"%%":function(){return"%"}};for(r in n)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),n[r](e)));r=
rb(c,!1);if(r.length>b)return 0;H.set(r,a);return r.length-1}function lc(a,b,c,e){a||(a=this);this.parent=a;this.Qa=a.Qa;this.wb=null;this.id=S.Zc++;this.name=b;this.mode=c;this.Ma={};this.Na={};this.rdev=e}Object.defineProperties(lc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vc:{get:function(){return S.Sa(this.mode)}},Sb:{get:function(){return S.Ab(this.mode)}}});
S.wc=lc;S.gd();for(var vb,mc=Array(256),nc=0;256>nc;++nc)mc[nc]=String.fromCharCode(nc);Bb=mc;Hb=d.BindingError=Gb("BindingError");Ib=d.InternalError=Gb("InternalError");d.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Wb=d.UnboundTypeError=Gb("UnboundTypeError");function rb(a,b){var c=Array(va(a)+1);a=ra(a,c,0,c.length);b&&(c.length=a);return c}
var oc={c:function(a,b,c,e){B("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,e?I(e):"unknown function"])},a:function(a){return ub(a)},b:function(a){"uncaught_exception"in gb?gb.Wa++:gb.Wa=1;throw a;},G:function(){hb(63);return-1},m:function(a,b,c){xb=c;try{var e=zb(a);switch(b){case 0:var f=yb();return 0>f?-28:S.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=yb(),e.flags|=f,0;case 12:return f=yb(),K[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;
case 9:return hb(28),-1;default:return-28}}catch(h){return"undefined"!==typeof S&&h instanceof S.Ka||B(h),-h.Va}},L:function(a,b,c){xb=c;try{var e=zb(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=yb();return L[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=yb(),S.Rb(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:B("bad ioctl syscall "+
b)}}catch(h){return"undefined"!==typeof S&&h instanceof S.Ka||B(h),-h.Va}},F:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var e=wb[a];if(e&&b===e.Bd){var f=S.mb(e.fd);if(e.Jd&2){var h=e.flags,l=e.offset,m=G.slice(a,a+b);S.nb(f,m,l,b,h)}wb[a]=null;e.Dc&&Z(e.Dd)}c=0}return c}catch(p){return"undefined"!==typeof S&&p instanceof S.Ka||B(p),-p.Va}},M:function(a,b,c){xb=c;try{var e=I(a),f=yb();return S.open(e,b,f).fd}catch(h){return"undefined"!==typeof S&&h instanceof S.Ka||B(h),-h.Va}},z:function(a,
b,c,e,f){var h=Ab(c);b=U(b);X(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,m){return m?e:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var m=H;else if(2===c)m=K;else if(4===c)m=L;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[l>>h])},hb:null})},y:function(a,b){b=U(b);X(a,{name:b,fromWireType:function(c){var e=Y[c].value;Lb(c);return e},toWireType:function(c,e){return Mb(e)},argPackAdvance:8,readValueFromPointer:Nb,hb:null})},
j:function(a,b,c){c=Ab(c);b=U(b);X(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ob(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Pb(b,c),hb:null})},v:function(a,b,c,e,f,h){var l=Ub(b,c);a=U(a);f=Vb(e,f);Tb(a,function(){Zb("Cannot call "+a+" due to unbound types",l)},b-1);Jb(l,function(m){var p=[m[0],null].concat(m.slice(1)),n=m=a,r=f,t=p.length;2>t&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var x=null!==p[1]&&!1,k=!1,q=1;q<p.length;++q)if(null!==p[q]&&void 0===p[q].hb){k=!0;break}var v="void"!==p[0].name,y="",C="";for(q=0;q<t-2;++q)y+=(0!==q?", ":"")+"arg"+q,C+=(0!==q?", ":"")+"arg"+q+"Wired";n="return function "+Eb(n)+"("+y+") {\nif (arguments.length !== "+(t-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+(t-2)+" args!');\n}\n";k&&(n+="var destructors = [];\n");var ya=k?"destructors":"null";y="throwBindingError invoker fn runDestructors retType classParam".split(" ");
r=[W,r,h,Rb,p[0],p[1]];x&&(n+="var thisWired = classParam.toWireType("+ya+", this);\n");for(q=0;q<t-2;++q)n+="var arg"+q+"Wired = argType"+q+".toWireType("+ya+", arg"+q+"); // "+p[q+2].name+"\n",y.push("argType"+q),r.push(p[q+2]);x&&(C="thisWired"+(0<C.length?", ":"")+C);n+=(v?"var rv = ":"")+"invoker(fn"+(0<C.length?", ":"")+C+");\n";if(k)n+="runDestructors(destructors);\n";else for(q=x?1:2;q<p.length;++q)t=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==p[q].hb&&(n+=t+"_dtor("+t+"); // "+p[q].name+
"\n",y.push(t+"_dtor"),r.push(p[q].hb));v&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");y.push(n+"}\n");p=Qb(y).apply(null,r);q=b-1;if(!d.hasOwnProperty(m))throw new Ib("Replacing nonexistant public symbol");void 0!==d[m].bb&&void 0!==q?d[m].bb[q]=p:(d[m]=p,d[m].Ec=q);return[]})},e:function(a,b,c,e,f){function h(n){return n}b=U(b);-1===f&&(f=4294967295);var l=Ab(c);if(0===e){var m=32-8*c;h=function(n){return n<<m>>>m}}var p=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:h,toWireType:function(n,
r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+Ob(r)+'" to '+this.name);if(r<e||r>f)throw new TypeError('Passing a number "'+Ob(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return p?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:$b(b,l,0!==e),hb:null})},d:function(a,b,c){function e(h){h>>=2;var l=M;return new f(Ea,l[h+1],l[h])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=U(c);X(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{Tc:!0})},k:function(a,b){b=U(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(e){var f=M[e>>2];if(c){var h=G[e+4+f],l=0;0!=h&&(l=h,G[e+4+f]=0);var m=e+4;for(h=0;h<=f;++h){var p=e+4+h;if(0==G[p]){m=I(m);if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;m=p+1}}0!=l&&(G[e+4+f]=l)}else{n=Array(f);for(h=0;h<f;++h)n[h]=String.fromCharCode(G[e+4+h]);n=n.join("")}Z(e);
return n},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var h="string"===typeof f;h||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||W("Cannot pass non-string to std::string");var l=(c&&h?function(){return va(f)}:function(){return f.length})(),m=ub(4+l+1);M[m>>2]=l;if(c&&h)ra(f,G,m+4,l+1);else if(h)for(h=0;h<l;++h){var p=f.charCodeAt(h);255<p&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));G[m+4+h]=p}else for(h=0;h<l;++h)G[m+
4+h]=f[h];null!==e&&e.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Nb,hb:function(e){Z(e)}})},g:function(a,b,c){c=U(c);if(2===b){var e=xa;var f=za;var h=Aa;var l=function(){return Fa};var m=1}else 4===b&&(e=Ba,f=Ca,h=Da,l=function(){return M},m=2);X(a,{name:c,fromWireType:function(p){var n=M[p>>2],r=l(),t=r[p+4+n*b>>m],x=0;0!=t&&(x=t,r[p+4+n*b>>m]=0);var k=p+4;for(t=0;t<=n;++t){var q=p+4+t*b;if(0==r[q>>m]){k=e(k);if(void 0===v)var v=k;else v+=String.fromCharCode(0),v+=k;k=q+b}}0!=x&&
(r[p+4+n*b>>m]=x);Z(p);return v},toWireType:function(p,n){"string"!==typeof n&&W("Cannot pass non-string to C++ string type "+c);var r=h(n),t=ub(4+r+b);M[t>>2]=r>>m;f(n,t+4,r+b);null!==p&&p.push(Z,t);return t},argPackAdvance:8,readValueFromPointer:Nb,hb:function(p){Z(p)}})},A:function(a,b){b=U(b);X(a,{zd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},N:Lb,O:function(a){4<a&&(Y[a].Zb+=1)},B:function(a,b){var c=V[a];void 0===c&&W("_emval_take_value has unknown type "+
Xb(a));a=c.readValueFromPointer(b);return Mb(a)},f:function(){B()},H:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ac();else return hb(28),-1;L[b>>2]=a/1E3|0;L[b+4>>2]=a%1E3*1E6|0;return 0},w:function(a,b,c){G.copyWithin(a,b,b+c)},x:function(a){a>>>=0;var b=G.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{F.grow(Math.min(2147483648,e)-Ea.byteLength+65535>>>16);Ia(F.buffer);
var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},I:function(a,b){var c=0;cc().forEach(function(e,f){var h=b+c;f=L[a+4*f>>2]=h;for(h=0;h<e.length;++h)H[f++>>0]=e.charCodeAt(h);H[f>>0]=0;c+=e.length+1});return 0},J:function(a,b){var c=cc();L[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});L[b>>2]=e;return 0},t:function(a){if(!noExitRuntime&&(na=!0,d.onExit))d.onExit(a);ca(a,new ja(a))},n:function(a){try{var b=zb(a);S.close(b);return 0}catch(c){return"undefined"!==typeof S&&c instanceof
S.Ka||B(c),c.Va}},K:function(a,b,c,e){try{a:{for(var f=zb(a),h=a=0;h<c;h++){var l=L[b+(8*h+4)>>2],m=S.read(f,H,L[b+8*h>>2],l,void 0);if(0>m){var p=-1;break a}a+=m;if(m<l)break}p=a}L[e>>2]=p;return 0}catch(n){return"undefined"!==typeof S&&n instanceof S.Ka||B(n),n.Va}},u:function(a,b,c,e,f){try{var h=zb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;S.Za(h,a,e);db=[h.position>>>0,(cb=h.position,1<=+Qa(cb)?0<cb?(Ta(+Sa(cb/4294967296),4294967295)|0)>>>0:~~+Ra((cb-+(~~cb>>>
0))/4294967296)>>>0:0)];L[f>>2]=db[0];L[f+4>>2]=db[1];h.Ob&&0===a&&0===e&&(h.Ob=null);return 0}catch(l){return"undefined"!==typeof S&&l instanceof S.Ka||B(l),l.Va}},o:function(a,b,c,e){try{a:{for(var f=zb(a),h=a=0;h<c;h++){var l=S.write(f,H,L[b+8*h>>2],L[b+(8*h+4)>>2],void 0);if(0>l){var m=-1;break a}a+=l}m=a}L[e>>2]=m;return 0}catch(p){return"undefined"!==typeof S&&p instanceof S.Ka||B(p),p.Va}},memory:F,q:function(){return 0},s:function(){return 0},r:function(){},h:function(){return 6},P:function(){},
p:function(){},l:function(){},D:function(){},C:function(){},i:function(){},E:function(a,b,c,e){return kc(a,b,c,e)},table:ma},pc=function(){function a(f){d.asm=f.exports;Xa()}function b(f){a(f.instance)}function c(f){return bb().then(function(h){return WebAssembly.instantiate(h,e)}).then(f,function(h){E("failed to asynchronously prepare wasm: "+h);B(h)})}var e={a:oc};Wa();if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(la||"function"!==typeof WebAssembly.instantiateStreaming||Za()||Ya("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(h){E("wasm streaming compile failed: "+h);E("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();d.asm=pc;var eb=d.___wasm_call_ctors=function(){return(eb=d.___wasm_call_ctors=d.asm.Q).apply(null,arguments)};
d._epub_open=function(){return(d._epub_open=d.asm.R).apply(null,arguments)};d._epub_count=function(){return(d._epub_count=d.asm.S).apply(null,arguments)};d.__Z10epub_imagei=function(){return(d.__Z10epub_imagei=d.asm.T).apply(null,arguments)};var ub=d._malloc=function(){return(ub=d._malloc=d.asm.U).apply(null,arguments)},Z=d._free=function(){return(Z=d._free=d.asm.V).apply(null,arguments)};d._analyse=function(){return(d._analyse=d.asm.W).apply(null,arguments)};
var ib=d.___errno_location=function(){return(ib=d.___errno_location=d.asm.X).apply(null,arguments)};d._version=function(){return(d._version=d.asm.Y).apply(null,arguments)};var Yb=d.___getTypeName=function(){return(Yb=d.___getTypeName=d.asm.Z).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm._).apply(null,arguments)};
var sa=d.stackSave=function(){return(sa=d.stackSave=d.asm.$).apply(null,arguments)},qa=d.stackAlloc=function(){return(qa=d.stackAlloc=d.asm.aa).apply(null,arguments)},ta=d.stackRestore=function(){return(ta=d.stackRestore=d.asm.ba).apply(null,arguments)};d.dynCall_iiii=function(){return(d.dynCall_iiii=d.asm.ca).apply(null,arguments)};d.dynCall_vii=function(){return(d.dynCall_vii=d.asm.da).apply(null,arguments)};d.dynCall_iii=function(){return(d.dynCall_iii=d.asm.ea).apply(null,arguments)};
d.dynCall_ii=function(){return(d.dynCall_ii=d.asm.fa).apply(null,arguments)};d.dynCall_vi=function(){return(d.dynCall_vi=d.asm.ga).apply(null,arguments)};d.dynCall_viiiiiii=function(){return(d.dynCall_viiiiiii=d.asm.ha).apply(null,arguments)};d.dynCall_v=function(){return(d.dynCall_v=d.asm.ia).apply(null,arguments)};d.dynCall_viii=function(){return(d.dynCall_viii=d.asm.ja).apply(null,arguments)};d.dynCall_viijii=function(){return(d.dynCall_viijii=d.asm.ka).apply(null,arguments)};
d.dynCall_viiii=function(){return(d.dynCall_viiii=d.asm.la).apply(null,arguments)};d.dynCall_ji=function(){return(d.dynCall_ji=d.asm.ma).apply(null,arguments)};d.dynCall_viiiiii=function(){return(d.dynCall_viiiiii=d.asm.na).apply(null,arguments)};d.dynCall_viiiii=function(){return(d.dynCall_viiiii=d.asm.oa).apply(null,arguments)};d.dynCall_viiiiiiiii=function(){return(d.dynCall_viiiiiiiii=d.asm.pa).apply(null,arguments)};
d.dynCall_viiiiiiii=function(){return(d.dynCall_viiiiiiii=d.asm.qa).apply(null,arguments)};d.dynCall_viiiiiiiiii=function(){return(d.dynCall_viiiiiiiiii=d.asm.ra).apply(null,arguments)};d.dynCall_viiiiiiiddi=function(){return(d.dynCall_viiiiiiiddi=d.asm.sa).apply(null,arguments)};d.dynCall_viiiiiiiiiiddi=function(){return(d.dynCall_viiiiiiiiiiddi=d.asm.ta).apply(null,arguments)};d.dynCall_viiid=function(){return(d.dynCall_viiid=d.asm.ua).apply(null,arguments)};
d.dynCall_viiiid=function(){return(d.dynCall_viiiid=d.asm.va).apply(null,arguments)};d.dynCall_viidi=function(){return(d.dynCall_viidi=d.asm.wa).apply(null,arguments)};d.dynCall_vidii=function(){return(d.dynCall_vidii=d.asm.xa).apply(null,arguments)};d.dynCall_iiiiiiiii=function(){return(d.dynCall_iiiiiiiii=d.asm.ya).apply(null,arguments)};d.dynCall_iiiii=function(){return(d.dynCall_iiiii=d.asm.za).apply(null,arguments)};d.dynCall_iiiiii=function(){return(d.dynCall_iiiiii=d.asm.Aa).apply(null,arguments)};
d.dynCall_viiiiiiiiidd=function(){return(d.dynCall_viiiiiiiiidd=d.asm.Ba).apply(null,arguments)};d.dynCall_jiji=function(){return(d.dynCall_jiji=d.asm.Ca).apply(null,arguments)};d.dynCall_iidiiii=function(){return(d.dynCall_iidiiii=d.asm.Da).apply(null,arguments)};d.dynCall_iiiiiii=function(){return(d.dynCall_iiiiiii=d.asm.Ea).apply(null,arguments)};d.dynCall_iiiiij=function(){return(d.dynCall_iiiiij=d.asm.Fa).apply(null,arguments)};
d.dynCall_iiiiid=function(){return(d.dynCall_iiiiid=d.asm.Ga).apply(null,arguments)};d.dynCall_iiiiijj=function(){return(d.dynCall_iiiiijj=d.asm.Ha).apply(null,arguments)};d.dynCall_iiiiiiii=function(){return(d.dynCall_iiiiiiii=d.asm.Ia).apply(null,arguments)};d.dynCall_iiiiiijj=function(){return(d.dynCall_iiiiiijj=d.asm.Ja).apply(null,arguments)};d.asm=pc;d.cwrap=function(a,b,c,e){c=c||[];var f=c.every(function(h){return"number"===h});return"string"!==b&&f&&!e?oa(a):function(){return pa(a,b,c,arguments)}};
d.FS=S;var qc;d.then=function(a){if(qc)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Va=function rc(){qc||sc();qc||(Va=rc)};
function sc(){function a(){if(!qc&&(qc=!0,d.calledRun=!0,!na)){d.noFSInit||S.sb.Qb||S.sb();Ka(Ma);S.rc=!1;Ka(Na);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Oa.unshift(b)}Ka(Oa)}}if(!(0<N)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Pa();Ka(La);0<N||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);a()},1)):a())}}d.run=sc;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();noExitRuntime=!0;sc();


  return Module
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    