
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},g;for(g in e)e.hasOwnProperty(g)&&(aa[g]=e[g]);var ba="./this.program";function ca(a,b){throw b;}var da=!1,u=!1,ea=!1,fa=!1;da="object"===typeof window;u="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!u;var v="",ha,ia,ja,ka;
if(ea)v=u?require("path").dirname(v)+"/":__dirname+"/",ha=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);return ja.readFileSync(a,b?null:"utf8")},ia=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof la))throw a;}),process.on("unhandledRejection",y),ca=function(a){process.exit(a)},e.inspect=
function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=typeof read&&(ha=function(a){return read(a)}),ia=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(ca=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||u)u?v=self.location.href:
document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ma=e.print||console.log.bind(console),A=e.printErr||console.warn.bind(console);
for(g in aa)aa.hasOwnProperty(g)&&(e[g]=aa[g]);aa=null;e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);var na=0,oa;e.wasmBinary&&(oa=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,pa=new WebAssembly.Table({initial:2980,maximum:2980,element:"anyfunc"}),qa=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function ra(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function sa(a,b,c,d){var f={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;q=ta(t);ua(n,C,q,t)}return q},array:function(n){var q=ta(n.length);E.set(n,q);return q}},h=ra(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var p=f[c[m]];p?(0===a&&(a=F()),k[m]=p(d[m])):k[m]=d[m]}c=h.apply(null,k);c=function(n){return"string"===b?G(n):"boolean"===b?!!n:n}(c);0!==a&&I(a);return c}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&va)return va.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function G(a){return a?wa(C,a,void 0):""}
function ua(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function za(a){var b;for(b=a>>1;J[b];)++b;b<<=1;if(32<b-a&&ya)return ya.decode(C.subarray(a,b));b=0;for(var c="";;){var d=J[a+2*b>>1];if(0==d)return c;++b;c+=String.fromCharCode(d)}}
function Aa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)J[b>>1]=a.charCodeAt(f),b+=2;J[b>>1]=0;return b-d}function Ba(a){return 2*a.length}function Ca(a){for(var b=0,c="";;){var d=K[a+4*b>>2];if(0==d)return c;++b;65536<=d?(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023)):c+=String.fromCharCode(d)}}
function Da(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}K[b>>2]=h;b+=4;if(b+4>c)break}K[b>>2]=0;return b-d}function Fa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ga,E,C,J,Ha,K,L,Ia,Ja;
function Ka(a){Ga=a;e.HEAP8=E=new Int8Array(a);e.HEAP16=J=new Int16Array(a);e.HEAP32=K=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=Ha=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=Ia=new Float32Array(a);e.HEAPF64=Ja=new Float64Array(a)}var La=e.INITIAL_MEMORY||16777216;e.wasmMemory?B=e.wasmMemory:B=new WebAssembly.Memory({initial:La/65536,maximum:32768});B&&(Ga=B.buffer);La=Ga.byteLength;Ka(Ga);K[374008]=6739072;
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Kd;"number"===typeof c?void 0===b.Dc?e.dynCall_v(c):e.dynCall_vi(c,b.Dc):c(void 0===b.Dc?null:b.Dc)}}}var Na=[],Oa=[],Pa=[],Qa=[];function Ra(){var a=e.preRun.shift();Na.unshift(a)}var Sa=Math.abs,Ta=Math.ceil,Ua=Math.floor,Va=Math.min,Wa=0,Xa=null,Ya=null;function Za(){Wa++;e.monitorRunDependencies&&e.monitorRunDependencies(Wa)}
function $a(){Wa--;e.monitorRunDependencies&&e.monitorRunDependencies(Wa);if(0==Wa&&(null!==Xa&&(clearInterval(Xa),Xa=null),Ya)){var a=Ya;Ya=null;a()}}e.preloadedImages={};e.preloadedAudios={};function y(a){if(e.onAbort)e.onAbort(a);ma(a);A(a);qa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function ab(a){var b=bb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function cb(){return ab("data:application/octet-stream;base64,")}var bb="../wasm/plugin.wasm";if(!cb()){var db=bb;bb=e.locateFile?e.locateFile(db,v):v+db}function eb(){try{if(oa)return new Uint8Array(oa);if(ia)return ia(bb);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}
function fb(){return oa||!da&&!u||"function"!==typeof fetch||ab("file://")?new Promise(function(a){a(eb())}):fetch(bb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+bb+"'";return a.arrayBuffer()}).catch(function(){return eb()})}var M,N;Oa.push({Kd:function(){gb()}});function hb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}var ib;
ea?ib=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ib=dateNow:ib=function(){return performance.now()};function jb(a){return K[kb()>>2]=a}function lb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ib();else return jb(28),-1;K[b>>2]=a/1E3|0;K[b+4>>2]=a%1E3*1E6|0;return 0}function mb(){return 0<mb.Ob}
function nb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ob(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=nb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function pb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function O(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function qb(){var a=Array.prototype.slice.call(arguments,0);return ob(a.join("/"))}function P(a,b){return ob(a+"/"+b)}
function Q(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:R.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=nb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function rb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var p=k.length-1;0<=p&&""===k[p];p--);return m>p?[]:k.slice(m,p-m+1)}a=Q(a).substr(1);b=Q(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,h=0;h<d;h++)if(a[h]!==b[h]){f=h;break}d=[];for(h=f;h<a.length;h++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var sb=[];function tb(a,b){sb[a]={input:[],output:[],ic:b};R.Tc(a,ub)}
var ub={open:function(a){var b=sb[a.node.rdev];if(!b)throw new R.Cb(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ic.flush(a.tty)},flush:function(a){a.tty.ic.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ic.gd)throw new R.Cb(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.ic.gd(a.tty)}catch(m){throw new R.Cb(29);}if(void 0===k&&0===f)throw new R.Cb(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.ic.Pc)throw new R.Cb(60);
try{for(var f=0;f<d;f++)a.tty.ic.Pc(a.tty,b[c+f])}catch(h){throw new R.Cb(29);}d&&(a.node.timestamp=Date.now());return f}},wb={gd:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.Ob?Buffer.Ob(256):new Buffer(256),d=0;try{d=ja.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=vb(b,!0)}return a.input.shift()},Pc:function(a,b){null===b||10===b?(ma(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ma(wa(a.output,0)),a.output=[])}},xb={Pc:function(a,b){null===b||10===b?(A(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(wa(a.output,0)),a.output=[])}},S={Ub:null,Jb:function(){return S.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(R.Nd(c)||R.isFIFO(c))throw new R.Cb(63);S.Ub||(S.Ub={dir:{node:{Rb:S.Eb.Rb,Mb:S.Eb.Mb,lookup:S.Eb.lookup,Xb:S.Eb.Xb,rename:S.Eb.rename,unlink:S.Eb.unlink,rmdir:S.Eb.rmdir,readdir:S.Eb.readdir,symlink:S.Eb.symlink},stream:{Sb:S.Fb.Sb}},file:{node:{Rb:S.Eb.Rb,Mb:S.Eb.Mb},stream:{Sb:S.Fb.Sb,read:S.Fb.read,write:S.Fb.write,lc:S.Fb.lc,fc:S.Fb.fc,hc:S.Fb.hc}},link:{node:{Rb:S.Eb.Rb,Mb:S.Eb.Mb,readlink:S.Eb.readlink},stream:{}},Xc:{node:{Rb:S.Eb.Rb,Mb:S.Eb.Mb},
stream:R.Ad}});c=R.createNode(a,b,c,d);R.Kb(c.mode)?(c.Eb=S.Ub.dir.node,c.Fb=S.Ub.dir.stream,c.Db={}):R.isFile(c.mode)?(c.Eb=S.Ub.file.node,c.Fb=S.Ub.file.stream,c.Gb=0,c.Db=null):R.ec(c.mode)?(c.Eb=S.Ub.link.node,c.Fb=S.Ub.link.stream):R.sc(c.mode)&&(c.Eb=S.Ub.Xc.node,c.Fb=S.Ub.Xc.stream);c.timestamp=Date.now();a&&(a.Db[b]=c);return c},re:function(a){if(a.Db&&a.Db.subarray){for(var b=[],c=0;c<a.Gb;++c)b.push(a.Db[c]);return b}return a.Db},se:function(a){return a.Db?a.Db.subarray?a.Db.subarray(0,
a.Gb):new Uint8Array(a.Db):new Uint8Array(0)},bd:function(a,b){var c=a.Db?a.Db.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Db,a.Db=new Uint8Array(b),0<a.Gb&&a.Db.set(c.subarray(0,a.Gb),0))},ae:function(a,b){if(a.Gb!=b)if(0==b)a.Db=null,a.Gb=0;else{if(!a.Db||a.Db.subarray){var c=a.Db;a.Db=new Uint8Array(b);c&&a.Db.set(c.subarray(0,Math.min(b,a.Gb)))}else if(a.Db||(a.Db=[]),a.Db.length>b)a.Db.length=b;else for(;a.Db.length<b;)a.Db.push(0);a.Gb=b}},Eb:{Rb:function(a){var b=
{};b.dev=R.sc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;R.Kb(a.mode)?b.size=4096:R.isFile(a.mode)?b.size=a.Gb:R.ec(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.yd=4096;b.blocks=Math.ceil(b.size/b.yd);return b},Mb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.ae(a,b.size)},lookup:function(){throw R.Gc[44];},Xb:function(a,
b,c,d){return S.createNode(a,b,c,d)},rename:function(a,b,c){if(R.Kb(a.mode)){try{var d=R.Wb(b,c)}catch(h){}if(d)for(var f in d.Db)throw new R.Cb(55);}delete a.parent.Db[a.name];a.name=c;b.Db[c]=a;a.parent=b},unlink:function(a,b){delete a.Db[b]},rmdir:function(a,b){var c=R.Wb(a,b),d;for(d in c.Db)throw new R.Cb(55);delete a.Db[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Db)a.Db.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!R.ec(a.mode))throw new R.Cb(28);
return a.link}},Fb:{read:function(a,b,c,d,f){var h=a.node.Db;if(f>=a.node.Gb)return 0;a=Math.min(a.node.Gb-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){b.buffer===E.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Db||a.Db.subarray)){if(h)return a.Db=b.subarray(c,c+d),a.Gb=d;if(0===a.Gb&&0===f)return a.Db=b.slice(c,c+d),a.Gb=d;if(f+d<=a.Gb)return a.Db.set(b.subarray(c,c+d),f),d}S.bd(a,f+
d);if(a.Db.subarray&&b.subarray)a.Db.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.Db[f+h]=b[c+h];a.Gb=Math.max(a.Gb,f+d);return d},Sb:function(a,b,c){1===c?b+=a.position:2===c&&R.isFile(a.node.mode)&&(b+=a.node.Gb);if(0>b)throw new R.Cb(28);return b},lc:function(a,b,c){S.bd(a.node,b+c);a.node.Gb=Math.max(a.node.Gb,b+c)},fc:function(a,b,c,d,f,h,k){if(!R.isFile(a.node.mode))throw new R.Cb(43);a=a.node.Db;if(k&2||a.buffer!==b.buffer){if(0<f||f+d<a.length)a.subarray?a=a.subarray(f,f+d):a=Array.prototype.slice.call(a,
f,f+d);f=!0;k=b.buffer==E.buffer;d=yb(d);if(!d)throw new R.Cb(48);(k?E:b).set(a,d)}else f=!1,d=a.byteOffset;return{$d:d,Bc:f}},hc:function(a,b,c,d,f){if(!R.isFile(a.node.mode))throw new R.Cb(43);if(f&2)return 0;S.Fb.write(a,b,0,d,c,!1);return 0}}},R={root:null,pc:[],$c:{},streams:[],Ud:1,Tb:null,Zc:"/",Jc:!1,ld:!0,Lb:{},pd:{nd:{td:1,ud:2}},Cb:null,Gc:{},Id:null,wc:0,te:function(a){if(!(a instanceof R.Cb)){a:{var b=Error();if(!b.stack){try{throw Error();}catch(c){b=c}if(!b.stack){b="(no stack trace available)";
break a}}b=b.stack.toString()}e.extraStackTrace&&(b+="\n"+e.extraStackTrace());b=hb(b);throw a+" : "+b;}return jb(a.Ib)},Hb:function(a,b){a=Q(R.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Fc:!0,Rc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Rc)throw new R.Cb(32);a=nb(a.split("/").filter(function(k){return!!k}),!1);var f=R.root;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;f=R.Wb(f,a[d]);c=P(c,a[d]);R.ac(f)&&(!h||h&&b.Fc)&&(f=f.oc.root);if(!h||b.Pb)for(h=
0;R.ec(f.mode);)if(f=R.readlink(c),c=Q(pb(c),f),f=R.Hb(c,{Rc:b.Rc}).node,40<h++)throw new R.Cb(32);}return{path:c,node:f}},Qb:function(a){for(var b;;){if(R.tc(a))return a=a.Jb.md,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ic:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.Tb.length},jd:function(a){var b=R.Ic(a.parent.id,a.name);a.cc=R.Tb[b];R.Tb[b]=a},kd:function(a){var b=R.Ic(a.parent.id,a.name);if(R.Tb[b]===a)R.Tb[b]=a.cc;
else for(b=R.Tb[b];b;){if(b.cc===a){b.cc=a.cc;break}b=b.cc}},Wb:function(a,b){var c=R.Rd(a);if(c)throw new R.Cb(c,a);for(c=R.Tb[R.Ic(a.id,b)];c;c=c.cc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return R.lookup(a,b)},createNode:function(a,b,c,d){a=new R.rd(a,b,c,d);R.jd(a);return a},Ec:function(a){R.kd(a)},tc:function(a){return a===a.parent},ac:function(a){return!!a.oc},isFile:function(a){return 32768===(a&61440)},Kb:function(a){return 16384===(a&61440)},ec:function(a){return 40960===(a&61440)},
sc:function(a){return 8192===(a&61440)},Nd:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Jd:{r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218},Td:function(a){var b=R.Jd[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},cd:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},dc:function(a,b){if(R.ld)return 0;
if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0},Rd:function(a){var b=R.dc(a,"x");return b?b:a.Eb.lookup?0:2},Oc:function(a,b){try{return R.Wb(a,b),20}catch(c){}return R.dc(a,"wx")},uc:function(a,b,c){try{var d=R.Wb(a,b)}catch(f){return f.Ib}if(a=R.dc(a,"wx"))return a;if(c){if(!R.Kb(d.mode))return 54;if(R.tc(d)||R.Qb(d)===R.cwd())return 10}else if(R.Kb(d.mode))return 31;return 0},Sd:function(a,b){return a?
R.ec(a.mode)?32:R.Kb(a.mode)&&("r"!==R.cd(b)||b&512)?31:R.dc(a,R.cd(b)):44},sd:4096,Vd:function(a,b){b=b||R.sd;for(a=a||0;a<=b;a++)if(!R.streams[a])return a;throw new R.Cb(33);},$b:function(a){return R.streams[a]},Hd:function(a,b,c){R.Ac||(R.Ac=function(){},R.Ac.prototype={object:{get:function(){return this.node},set:function(h){this.node=h}}});var d=new R.Ac,f;for(f in a)d[f]=a[f];a=d;b=R.Vd(b,c);a.fd=b;return R.streams[b]=a},Bd:function(a){R.streams[a]=null},Ad:{open:function(a){a.Fb=R.Ld(a.node.rdev).Fb;
a.Fb.open&&a.Fb.open(a)},Sb:function(){throw new R.Cb(70);}},Nc:function(a){return a>>8},xe:function(a){return a&255},bc:function(a,b){return a<<8|b},Tc:function(a,b){R.$c[a]={Fb:b}},Ld:function(a){return R.$c[a]},ed:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.pc)}return b},od:function(a,b){function c(k){R.wc--;return b(k)}function d(k){if(k){if(!d.Ob)return d.Ob=!0,c(k)}else++h>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);R.wc++;1<R.wc&&A("warning: "+
R.wc+" FS.syncfs operations in flight at once, probably just doing extra work");var f=R.ed(R.root.Jb),h=0;f.forEach(function(k){if(!k.type.od)return d(null);k.type.od(k,a,d)})},Jb:function(a,b,c){var d="/"===c,f=!c;if(d&&R.root)throw new R.Cb(10);if(!d&&!f){var h=R.Hb(c,{Fc:!1});c=h.path;h=h.node;if(R.ac(h))throw new R.Cb(10);if(!R.Kb(h.mode))throw new R.Cb(54);}b={type:a,Be:b,md:c,pc:[]};a=a.Jb(b);a.Jb=b;b.root=a;d?R.root=a:h&&(h.oc=b,h.Jb&&h.Jb.pc.push(b));return a},Fe:function(a){a=R.Hb(a,{Fc:!1});
if(!R.ac(a.node))throw new R.Cb(28);a=a.node;var b=a.oc,c=R.ed(b);Object.keys(R.Tb).forEach(function(d){for(d=R.Tb[d];d;){var f=d.cc;-1!==c.indexOf(d.Jb)&&R.Ec(d);d=f}});a.oc=null;a.Jb.pc.splice(a.Jb.pc.indexOf(b),1)},lookup:function(a,b){return a.Eb.lookup(a,b)},Xb:function(a,b,c){var d=R.Hb(a,{parent:!0}).node;a=O(a);if(!a||"."===a||".."===a)throw new R.Cb(28);var f=R.Oc(d,a);if(f)throw new R.Cb(f);if(!d.Eb.Xb)throw new R.Cb(63);return d.Eb.Xb(d,a,b,c)},create:function(a,b){return R.Xb(a,(void 0!==
b?b:438)&4095|32768,0)},mkdir:function(a,b){return R.Xb(a,(void 0!==b?b:511)&1023|16384,0)},ye:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{R.mkdir(c,b)}catch(f){if(20!=f.Ib)throw f;}}},vc:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return R.Xb(a,b|8192,c)},symlink:function(a,b){if(!Q(a))throw new R.Cb(44);var c=R.Hb(b,{parent:!0}).node;if(!c)throw new R.Cb(44);b=O(b);var d=R.Oc(c,b);if(d)throw new R.Cb(d);if(!c.Eb.symlink)throw new R.Cb(63);return c.Eb.symlink(c,
b,a)},rename:function(a,b){var c=pb(a),d=pb(b),f=O(a),h=O(b);try{var k=R.Hb(a,{parent:!0});var m=k.node;k=R.Hb(b,{parent:!0});var p=k.node}catch(q){throw new R.Cb(10);}if(!m||!p)throw new R.Cb(44);if(m.Jb!==p.Jb)throw new R.Cb(75);k=R.Wb(m,f);d=rb(a,d);if("."!==d.charAt(0))throw new R.Cb(28);d=rb(b,c);if("."!==d.charAt(0))throw new R.Cb(55);try{var n=R.Wb(p,h)}catch(q){}if(k!==n){c=R.Kb(k.mode);if(f=R.uc(m,f,c))throw new R.Cb(f);if(f=n?R.uc(p,h,c):R.Oc(p,h))throw new R.Cb(f);if(!m.Eb.rename)throw new R.Cb(63);
if(R.ac(k)||n&&R.ac(n))throw new R.Cb(10);if(p!==m&&(f=R.dc(m,"w")))throw new R.Cb(f);try{R.Lb.willMovePath&&R.Lb.willMovePath(a,b)}catch(q){A("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+q.message)}R.kd(k);try{m.Eb.rename(k,p,h)}catch(q){throw q;}finally{R.jd(k)}try{if(R.Lb.onMovePath)R.Lb.onMovePath(a,b)}catch(q){A("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+q.message)}}},rmdir:function(a){var b=R.Hb(a,{parent:!0}).node,c=O(a),d=R.Wb(b,
c),f=R.uc(b,c,!0);if(f)throw new R.Cb(f);if(!b.Eb.rmdir)throw new R.Cb(63);if(R.ac(d))throw new R.Cb(10);try{R.Lb.willDeletePath&&R.Lb.willDeletePath(a)}catch(h){A("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Eb.rmdir(b,c);R.Ec(d);try{if(R.Lb.onDeletePath)R.Lb.onDeletePath(a)}catch(h){A("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readdir:function(a){a=R.Hb(a,{Pb:!0}).node;if(!a.Eb.readdir)throw new R.Cb(54);return a.Eb.readdir(a)},
unlink:function(a){var b=R.Hb(a,{parent:!0}).node,c=O(a),d=R.Wb(b,c),f=R.uc(b,c,!1);if(f)throw new R.Cb(f);if(!b.Eb.unlink)throw new R.Cb(63);if(R.ac(d))throw new R.Cb(10);try{R.Lb.willDeletePath&&R.Lb.willDeletePath(a)}catch(h){A("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Eb.unlink(b,c);R.Ec(d);try{if(R.Lb.onDeletePath)R.Lb.onDeletePath(a)}catch(h){A("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readlink:function(a){a=R.Hb(a).node;
if(!a)throw new R.Cb(44);if(!a.Eb.readlink)throw new R.Cb(28);return Q(R.Qb(a.parent),a.Eb.readlink(a))},stat:function(a,b){a=R.Hb(a,{Pb:!b}).node;if(!a)throw new R.Cb(44);if(!a.Eb.Rb)throw new R.Cb(63);return a.Eb.Rb(a)},lstat:function(a){return R.stat(a,!0)},chmod:function(a,b,c){var d;"string"===typeof a?d=R.Hb(a,{Pb:!c}).node:d=a;if(!d.Eb.Mb)throw new R.Cb(63);d.Eb.Mb(d,{mode:b&4095|d.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){R.chmod(a,b,!0)},fchmod:function(a,b){a=R.$b(a);if(!a)throw new R.Cb(8);
R.chmod(a.node,b)},chown:function(a,b,c,d){var f;"string"===typeof a?f=R.Hb(a,{Pb:!d}).node:f=a;if(!f.Eb.Mb)throw new R.Cb(63);f.Eb.Mb(f,{timestamp:Date.now()})},lchown:function(a,b,c){R.chown(a,b,c,!0)},fchown:function(a,b,c){a=R.$b(a);if(!a)throw new R.Cb(8);R.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new R.Cb(28);var c;"string"===typeof a?c=R.Hb(a,{Pb:!0}).node:c=a;if(!c.Eb.Mb)throw new R.Cb(63);if(R.Kb(c.mode))throw new R.Cb(31);if(!R.isFile(c.mode))throw new R.Cb(28);if(a=R.dc(c,
"w"))throw new R.Cb(a);c.Eb.Mb(c,{size:b,timestamp:Date.now()})},qe:function(a,b){a=R.$b(a);if(!a)throw new R.Cb(8);if(0===(a.flags&2097155))throw new R.Cb(28);R.truncate(a.node,b)},Ge:function(a,b,c){a=R.Hb(a,{Pb:!0}).node;a.Eb.Mb(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new R.Cb(44);b="string"===typeof b?R.Td(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=ob(a);try{h=R.Hb(a,{Pb:!(b&131072)}).node}catch(m){}}var k=!1;if(b&
64)if(h){if(b&128)throw new R.Cb(20);}else h=R.Xb(a,c,0),k=!0;if(!h)throw new R.Cb(44);R.sc(h.mode)&&(b&=-513);if(b&65536&&!R.Kb(h.mode))throw new R.Cb(54);if(!k&&(c=R.Sd(h,b)))throw new R.Cb(c);b&512&&R.truncate(h,0);b&=-131713;d=R.Hd({node:h,path:R.Qb(h),flags:b,seekable:!0,position:0,Fb:h.Fb,he:[],error:!1},d,f);d.Fb.open&&d.Fb.open(d);!e.logReadFiles||b&1||(R.Qc||(R.Qc={}),a in R.Qc||(R.Qc[a]=1,A("FS.trackingDelegate error on read file: "+a)));try{R.Lb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=R.pd.nd.td),
0!==(b&2097155)&&(f|=R.pd.nd.ud),R.Lb.onOpenFile(a,f))}catch(m){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(R.nc(a))throw new R.Cb(8);a.Hc&&(a.Hc=null);try{a.Fb.close&&a.Fb.close(a)}catch(b){throw b;}finally{R.Bd(a.fd)}a.fd=null},nc:function(a){return null===a.fd},Sb:function(a,b,c){if(R.nc(a))throw new R.Cb(8);if(!a.seekable||!a.Fb.Sb)throw new R.Cb(70);if(0!=c&&1!=c&&2!=c)throw new R.Cb(28);a.position=a.Fb.Sb(a,b,c);a.he=[];
return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new R.Cb(28);if(R.nc(a))throw new R.Cb(8);if(1===(a.flags&2097155))throw new R.Cb(8);if(R.Kb(a.node.mode))throw new R.Cb(31);if(!a.Fb.read)throw new R.Cb(28);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new R.Cb(70);b=a.Fb.read(a,b,c,d,f);h||(a.position+=b);return b},write:function(a,b,c,d,f,h){if(0>d||0>f)throw new R.Cb(28);if(R.nc(a))throw new R.Cb(8);if(0===(a.flags&2097155))throw new R.Cb(8);if(R.Kb(a.node.mode))throw new R.Cb(31);
if(!a.Fb.write)throw new R.Cb(28);a.seekable&&a.flags&1024&&R.Sb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new R.Cb(70);b=a.Fb.write(a,b,c,d,f,h);k||(a.position+=b);try{if(a.path&&R.Lb.onWriteToFile)R.Lb.onWriteToFile(a.path)}catch(m){A("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},lc:function(a,b,c){if(R.nc(a))throw new R.Cb(8);if(0>b||0>=c)throw new R.Cb(28);if(0===(a.flags&2097155))throw new R.Cb(8);if(!R.isFile(a.node.mode)&&
!R.Kb(a.node.mode))throw new R.Cb(43);if(!a.Fb.lc)throw new R.Cb(138);a.Fb.lc(a,b,c)},fc:function(a,b,c,d,f,h,k){if(0!==(h&2)&&0===(k&2)&&2!==(a.flags&2097155))throw new R.Cb(2);if(1===(a.flags&2097155))throw new R.Cb(2);if(!a.Fb.fc)throw new R.Cb(43);return a.Fb.fc(a,b,c,d,f,h,k)},hc:function(a,b,c,d,f){return a&&a.Fb.hc?a.Fb.hc(a,b,c,d,f):0},ze:function(){return 0},Kc:function(a,b,c){if(!a.Fb.Kc)throw new R.Cb(59);return a.Fb.Kc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||"r";b.encoding=
b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=R.open(a,b.flags);a=R.stat(a).size;var f=new Uint8Array(a);R.read(d,f,0,a,0);"utf8"===b.encoding?c=wa(f,0):"binary"===b.encoding&&(c=f);R.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||"w";a=R.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(xa(b)+1);b=ua(b,d,0,d.length);R.write(a,d,0,b,void 0,c.zd)}else if(ArrayBuffer.isView(b))R.write(a,
b,0,b.byteLength,void 0,c.zd);else throw Error("Unsupported data type");R.close(a)},cwd:function(){return R.Zc},chdir:function(a){a=R.Hb(a,{Pb:!0});if(null===a.node)throw new R.Cb(44);if(!R.Kb(a.node.mode))throw new R.Cb(54);var b=R.dc(a.node,"x");if(b)throw new R.Cb(b);R.Zc=a.path},Dd:function(){R.mkdir("/tmp");R.mkdir("/home");R.mkdir("/home/web_user")},Cd:function(){R.mkdir("/dev");R.Tc(R.bc(1,3),{read:function(){return 0},write:function(d,f,h,k){return k}});R.vc("/dev/null",R.bc(1,3));tb(R.bc(5,
0),wb);tb(R.bc(6,0),xb);R.vc("/dev/tty",R.bc(5,0));R.vc("/dev/tty1",R.bc(6,0));if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){y("random_device")});R.Yb("/dev","random",b);R.Yb("/dev","urandom",b);R.mkdir("/dev/shm");R.mkdir("/dev/shm/tmp")},Fd:function(){R.mkdir("/proc");R.mkdir("/proc/self");
R.mkdir("/proc/self/fd");R.Jb({Jb:function(){var a=R.createNode("/proc/self","fd",16895,73);a.Eb={lookup:function(b,c){var d=R.$b(+c);if(!d)throw new R.Cb(8);b={parent:null,Jb:{md:"fake"},Eb:{readlink:function(){return d.path}}};return b.parent=b}};return a}},{},"/proc/self/fd")},Gd:function(){e.stdin?R.Yb("/dev","stdin",e.stdin):R.symlink("/dev/tty","/dev/stdin");e.stdout?R.Yb("/dev","stdout",null,e.stdout):R.symlink("/dev/tty","/dev/stdout");e.stderr?R.Yb("/dev","stderr",null,e.stderr):R.symlink("/dev/tty1",
"/dev/stderr");R.open("/dev/stdin","r");R.open("/dev/stdout","w");R.open("/dev/stderr","w")},ad:function(){R.Cb||(R.Cb=function(a,b){this.node=b;this.be=function(c){this.Ib=c};this.be(a);this.message="FS error"},R.Cb.prototype=Error(),R.Cb.prototype.constructor=R.Cb,[44].forEach(function(a){R.Gc[a]=new R.Cb(a);R.Gc[a].stack="<generic error, no stack>"}))},ce:function(){R.ad();R.Tb=Array(4096);R.Jb(S,{},"/");R.Dd();R.Cd();R.Fd();R.Id={MEMFS:S}},mc:function(a,b,c){R.mc.Jc=!0;R.ad();e.stdin=a||e.stdin;
e.stdout=b||e.stdout;e.stderr=c||e.stderr;R.Gd()},quit:function(){R.mc.Jc=!1;var a=e._fflush;a&&a(0);for(a=0;a<R.streams.length;a++){var b=R.streams[a];b&&R.close(b)}},rc:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},ve:function(a,b){a=qb.apply(null,a);b&&"/"==a[0]&&(a=a.substr(1));return a},ie:function(a,b){return Q(b,a)},De:function(a){return ob(a)},pe:function(a,b){a=R.Cc(a,b);if(a.exists)return a.object;jb(a.error);return null},Cc:function(a,b){try{var c=R.Hb(a,{Pb:!b});a=c.path}catch(f){}var d=
{tc:!1,exists:!1,error:0,name:null,path:null,object:null,Wd:!1,Yd:null,Xd:null};try{c=R.Hb(a,{parent:!0}),d.Wd=!0,d.Yd=c.path,d.Xd=c.node,d.name=O(a),c=R.Hb(a,{Pb:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.tc="/"===c.path}catch(f){d.error=f.Ib}return d},ke:function(a,b,c,d){a=P("string"===typeof a?a:R.Qb(a),b);return R.mkdir(a,R.rc(c,d))},ne:function(a,b){a="string"===typeof a?a:R.Qb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=P(a,c);try{R.mkdir(d)}catch(f){}a=
d}}return d},Ed:function(a,b,c,d,f){a=P("string"===typeof a?a:R.Qb(a),b);return R.create(a,R.rc(d,f))},Yc:function(a,b,c,d,f,h){a=b?P("string"===typeof a?a:R.Qb(a),b):a;d=R.rc(d,f);f=R.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}R.chmod(f,d|146);a=R.open(f,"w");R.write(a,c,0,c.length,0,h);R.close(a);R.chmod(f,d)}return f},Yb:function(a,b,c,d){a=P("string"===typeof a?a:R.Qb(a),b);b=R.rc(!!c,!!d);R.Yb.Nc||(R.Yb.Nc=64);var f=R.bc(R.Yb.Nc++,
0);R.Tc(f,{open:function(h){h.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(h,k,m,p){for(var n=0,q=0;q<p;q++){try{var t=c()}catch(x){throw new R.Cb(29);}if(void 0===t&&0===n)throw new R.Cb(6);if(null===t||void 0===t)break;n++;k[m+q]=t}n&&(h.node.timestamp=Date.now());return n},write:function(h,k,m,p){for(var n=0;n<p;n++)try{d(k[m+n])}catch(q){throw new R.Cb(29);}p&&(h.node.timestamp=Date.now());return n}});return R.vc(a,b,f)},me:function(a,b,c){a=P("string"===typeof a?
a:R.Qb(a),b);return R.symlink(c,a)},dd:function(a){if(a.Lc||a.Od||a.link||a.Db)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ha)try{a.Db=vb(ha(a.url),!0),a.Gb=a.Db.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||jb(29);return b},le:function(a,
b,c,d,f){function h(){this.Mc=!1;this.Ob=[]}h.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.chunkSize;return this.hd(n/this.chunkSize|0)[q]}};h.prototype.qd=function(n){this.hd=n};h.prototype.Wc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),t,x=(t=n.getResponseHeader("Accept-Ranges"))&&"bytes"===t;n=
(t=n.getResponseHeader("Content-Encoding"))&&"gzip"===t;var l=1048576;x||(l=q);var r=this;r.qd(function(w){var z=w*l,D=(w+1)*l-1;D=Math.min(D,q-1);if("undefined"===typeof r.Ob[w]){var Ea=r.Ob;if(z>D)throw Error("invalid range ("+z+", "+D+") or no bytes requested!");if(D>q-1)throw Error("only "+q+" bytes available! programmer error!");var H=new XMLHttpRequest;H.open("GET",c,!1);q!==l&&H.setRequestHeader("Range","bytes="+z+"-"+D);"undefined"!=typeof Uint8Array&&(H.responseType="arraybuffer");H.overrideMimeType&&
H.overrideMimeType("text/plain; charset=x-user-defined");H.send(null);if(!(200<=H.status&&300>H.status||304===H.status))throw Error("Couldn't load "+c+". Status: "+H.status);z=void 0!==H.response?new Uint8Array(H.response||[]):vb(H.responseText||"",!0);Ea[w]=z}if("undefined"===typeof r.Ob[w])throw Error("doXHR failed!");return r.Ob[w]});if(n||!q)l=q=1,l=q=this.hd(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.wd=q;this.vd=l;this.Mc=!0};if("undefined"!==
typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new h;Object.defineProperties(k,{length:{get:function(){this.Mc||this.Wc();return this.wd}},chunkSize:{get:function(){this.Mc||this.Wc();return this.vd}}});k={Lc:!1,Db:k}}else k={Lc:!1,url:c};var m=R.Ed(a,b,k,d,f);k.Db?m.Db=k.Db:k.url&&(m.Db=null,m.url=k.url);Object.defineProperties(m,{Gb:{get:function(){return this.Db.length}}});var p={};Object.keys(m.Fb).forEach(function(n){var q=
m.Fb[n];p[n]=function(){if(!R.dd(m))throw new R.Cb(29);return q.apply(null,arguments)}});p.read=function(n,q,t,x,l){if(!R.dd(m))throw new R.Cb(29);n=n.node.Db;if(l>=n.length)return 0;x=Math.min(n.length-l,x);if(n.slice)for(var r=0;r<x;r++)q[t+r]=n[l+r];else for(r=0;r<x;r++)q[t+r]=n.get(l+r);return x};m.Fb=p;return m},oe:function(a,b,c,d,f,h,k,m,p,n){function q(x){function l(w){n&&n();m||R.Yc(a,b,w,d,f,p);h&&h();$a()}var r=!1;e.preloadPlugins.forEach(function(w){!r&&w.canHandle(t)&&(w.handle(x,t,l,
function(){k&&k();$a()}),r=!0)});r||l(x)}zb.mc();var t=b?Q(P(a,b)):a;Za();"string"==typeof c?zb.je(c,function(x){q(x)},k):q(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Uc:function(){return"EM_FS_"+window.location.pathname},Vc:20,kc:"FILE_DATA",Ce:function(a,b,c){b=b||function(){};c=c||function(){};var d=R.indexedDB();try{var f=d.open(R.Uc(),R.Vc)}catch(h){return c(h)}f.onupgradeneeded=function(){ma("creating db");f.result.createObjectStore(R.kc)};
f.onsuccess=function(){var h=f.result.transaction([R.kc],"readwrite"),k=h.objectStore(R.kc),m=0,p=0,n=a.length;a.forEach(function(q){q=k.put(R.Cc(q).object.Db,q);q.onsuccess=function(){m++;m+p==n&&(0==p?b():c())};q.onerror=function(){p++;m+p==n&&(0==p?b():c())}});h.onerror=c};f.onerror=c},we:function(a,b,c){b=b||function(){};c=c||function(){};var d=R.indexedDB();try{var f=d.open(R.Uc(),R.Vc)}catch(h){return c(h)}f.onupgradeneeded=c;f.onsuccess=function(){var h=f.result;try{var k=h.transaction([R.kc],
"readonly")}catch(t){c(t);return}var m=k.objectStore(R.kc),p=0,n=0,q=a.length;a.forEach(function(t){var x=m.get(t);x.onsuccess=function(){R.Cc(t).exists&&R.unlink(t);R.Yc(pb(t),O(t),x.result,!0,!0,!0);p++;p+n==q&&(0==n?b():c())};x.onerror=function(){n++;p+n==q&&(0==n?b():c())}});k.onerror=c};f.onerror=c}},Ab={};
function Bb(a,b){var c=R.stat;try{var d=c(a)}catch(f){if(f&&f.node&&ob(a)!==ob(R.Qb(f.node)))return-54;throw f;}K[b>>2]=d.dev;K[b+4>>2]=0;K[b+8>>2]=d.ino;K[b+12>>2]=d.mode;K[b+16>>2]=d.nlink;K[b+20>>2]=d.uid;K[b+24>>2]=d.gid;K[b+28>>2]=d.rdev;K[b+32>>2]=0;N=[d.size>>>0,(M=d.size,1<=+Sa(M)?0<M?(Va(+Ua(M/4294967296),4294967295)|0)>>>0:~~+Ta((M-+(~~M>>>0))/4294967296)>>>0:0)];K[b+40>>2]=N[0];K[b+44>>2]=N[1];K[b+48>>2]=4096;K[b+52>>2]=d.blocks;K[b+56>>2]=d.atime.getTime()/1E3|0;K[b+60>>2]=0;K[b+64>>2]=
d.mtime.getTime()/1E3|0;K[b+68>>2]=0;K[b+72>>2]=d.ctime.getTime()/1E3|0;K[b+76>>2]=0;N=[d.ino>>>0,(M=d.ino,1<=+Sa(M)?0<M?(Va(+Ua(M/4294967296),4294967295)|0)>>>0:~~+Ta((M-+(~~M>>>0))/4294967296)>>>0:0)];K[b+80>>2]=N[0];K[b+84>>2]=N[1];return 0}var Cb=void 0;function Db(){Cb+=4;return K[Cb-4>>2]}function T(a){a=R.$b(a);if(!a)throw new R.Cb(8);return a}function Eb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}
var Fb=void 0;function U(a){for(var b="";C[a];)b+=Fb[C[a++]];return b}var Gb={},Hb={},Ib={};function Jb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Kb(a,b){a=Jb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Lb(a){var b=Error,c=Kb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Mb=void 0;function V(a){throw new Mb(a);}var Nb=void 0;
function Ob(a,b){function c(m){m=b(m);if(m.length!==d.length)throw new Nb("Mismatched type converter count");for(var p=0;p<d.length;++p)W(d[p],m[p])}var d=[];d.forEach(function(m){Ib[m]=a});var f=Array(a.length),h=[],k=0;a.forEach(function(m,p){Hb.hasOwnProperty(m)?f[p]=Hb[m]:(h.push(m),Gb.hasOwnProperty(m)||(Gb[m]=[]),Gb[m].push(function(){f[p]=Hb[m];++k;k===h.length&&c(f)}))});0===h.length&&c(f)}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Hb.hasOwnProperty(a)){if(c.Md)return;V("Cannot register type '"+d+"' twice")}Hb[a]=b;delete Ib[a];Gb.hasOwnProperty(a)&&(b=Gb[a],delete Gb[a],b.forEach(function(f){f()}))}var Pb=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Qb(a){4<a&&0===--X[a].Sc&&(X[a]=void 0,Pb.push(a))}function Rb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Pb.length?Pb.pop():X.length;X[b]={Sc:1,value:a};return b}}function Sb(a){return this.fromWireType(L[a>>2])}function Tb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ub(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ia[c>>2])};case 3:return function(c){return this.fromWireType(Ja[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Vb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Kb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Wb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Xb(a,b){var c=e;if(void 0===c[a].Vb){var d=c[a];c[a]=function(){c[a].Vb.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Vb+")!");return c[a].Vb[arguments.length].apply(this,arguments)};c[a].Vb=[];c[a].Vb[d.xd]=d}}
function Yb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].Vb&&void 0!==e[a].Vb[c])&&V("Cannot register public name '"+a+"' twice"),Xb(a,a),e.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].Vb[c]=b):(e[a]=b,void 0!==c&&(e[a].Ae=c))}function Zb(a,b){for(var c=[],d=0;d<a;d++)c.push(K[(b>>2)+d]);return c}
function $b(a,b){a=U(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var ac=void 0;function bc(a){a=cc(a);var b=U(a);Y(a);return b}
function dc(a,b){function c(h){f[h]||Hb[h]||(Ib[h]?Ib[h].forEach(c):(d.push(h),f[h]=!0))}var d=[],f={};b.forEach(c);throw new ac(a+": "+d.map(bc).join([", "]));}function ec(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return C[d]};case 1:return c?function(d){return J[d>>1]}:function(d){return Ha[d>>1]};case 2:return c?function(d){return K[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var fc=0;
function hc(a,b,c,d){a|=0;b|=0;c|=0;d|=0;var f=0;fc=fc+1|0;for(K[a>>2]=fc;(f|0)<(d|0);){if(0==(K[c+(f<<3)>>2]|0))return K[c+(f<<3)>>2]=fc,K[c+((f<<3)+4)>>2]=b,K[c+((f<<3)+8)>>2]=0,na=d|0,c|0;f=f+1|0}d=2*d|0;c=ic(c|0,8*(d+1|0)|0)|0;c=hc(a|0,b|0,c|0,d|0)|0;na=d|0;return c|0}var jc={};
function kc(){if(!lc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in jc)a[b]=jc[b];var c=[];for(b in a)c.push(b+"="+a[b]);lc=c}return lc}var lc;function mc(a){return 0===a%4&&(0!==a%100||0===a%400)}function nc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var oc=[31,29,31,30,31,30,31,31,30,31,30,31],pc=[31,28,31,30,31,30,31,31,30,31,30,31];function qc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(mc(a.getFullYear())?oc:pc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function rc(a,b,c,d){function f(l,r,w){for(l="number"===typeof l?l.toString():l||"";l.length<r;)l=w[0]+l;return l}function h(l,r){return f(l,r,"0")}function k(l,r){function w(D){return 0>D?-1:0<D?1:0}var z;0===(z=w(l.getFullYear()-r.getFullYear()))&&0===(z=w(l.getMonth()-r.getMonth()))&&(z=w(l.getDate()-r.getDate()));return z}function m(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function p(l){l=qc(new Date(l.Nb+1900,0,1),l.zc);var r=new Date(l.getFullYear()+1,0,4),w=m(new Date(l.getFullYear(),0,4));r=m(r);return 0>=k(w,l)?0>=k(r,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var n=K[d+40>>2];d={fe:K[d>>2],ee:K[d+4>>2],xc:K[d+8>>2],qc:K[d+12>>2],jc:K[d+16>>2],Nb:K[d+20>>2],yc:K[d+24>>2],zc:K[d+28>>2],Ee:K[d+32>>2],de:K[d+
36>>2],ge:n?G(n):""};c=G(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");n={"%a":function(l){return t[l.yc].substring(0,3)},"%A":function(l){return t[l.yc]},"%b":function(l){return x[l.jc].substring(0,3)},"%B":function(l){return x[l.jc]},"%C":function(l){return h((l.Nb+1900)/100|0,2)},"%d":function(l){return h(l.qc,2)},"%e":function(l){return f(l.qc,2," ")},"%g":function(l){return p(l).toString().substring(2)},"%G":function(l){return p(l)},"%H":function(l){return h(l.xc,
2)},"%I":function(l){l=l.xc;0==l?l=12:12<l&&(l-=12);return h(l,2)},"%j":function(l){return h(l.qc+nc(mc(l.Nb+1900)?oc:pc,l.jc-1),3)},"%m":function(l){return h(l.jc+1,2)},"%M":function(l){return h(l.ee,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.xc&&12>l.xc?"AM":"PM"},"%S":function(l){return h(l.fe,2)},"%t":function(){return"\t"},"%u":function(l){return l.yc||7},"%U":function(l){var r=new Date(l.Nb+1900,0,1),w=0===r.getDay()?r:qc(r,7-r.getDay());l=new Date(l.Nb+1900,l.jc,l.qc);return 0>
k(w,l)?h(Math.ceil((31-w.getDate()+(nc(mc(l.getFullYear())?oc:pc,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(w,r)?"01":"00"},"%V":function(l){var r=new Date(l.Nb+1901,0,4),w=m(new Date(l.Nb+1900,0,4));r=m(r);var z=qc(new Date(l.Nb+1900,0,1),l.zc);return 0>k(z,w)?"53":0>=k(r,z)?"01":h(Math.ceil((w.getFullYear()<l.Nb+1900?l.zc+32-w.getDate():l.zc+1-w.getDate())/7),2)},"%w":function(l){return l.yc},"%W":function(l){var r=new Date(l.Nb,0,1),w=1===r.getDay()?r:qc(r,0===r.getDay()?1:7-r.getDay()+1);l=
new Date(l.Nb+1900,l.jc,l.qc);return 0>k(w,l)?h(Math.ceil((31-w.getDate()+(nc(mc(l.getFullYear())?oc:pc,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(w,r)?"01":"00"},"%y":function(l){return(l.Nb+1900).toString().substring(2)},"%Y":function(l){return l.Nb+1900},"%z":function(l){l=l.de;var r=0<=l;l=Math.abs(l)/60;return(r?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.ge},"%%":function(){return"%"}};for(q in n)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));q=
vb(c,!1);if(q.length>b)return 0;E.set(q,a);return q.length-1}function sc(a,b,c,d){a||(a=this);this.parent=a;this.Jb=a.Jb;this.oc=null;this.id=R.Ud++;this.name=b;this.mode=c;this.Eb={};this.Fb={};this.rdev=d}Object.defineProperties(sc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Od:{get:function(){return R.Kb(this.mode)}},Lc:{get:function(){return R.sc(this.mode)}}});
R.rd=sc;R.ce();for(var zb,tc=Array(256),uc=0;256>uc;++uc)tc[uc]=String.fromCharCode(uc);Fb=tc;Mb=e.BindingError=Lb("BindingError");Nb=e.InternalError=Lb("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};ac=e.UnboundTypeError=Lb("UnboundTypeError");function vb(a,b){var c=Array(xa(a)+1);a=ua(a,c,0,c.length);b&&(c.length=a);return c}
var Ic={k:function(a,b,c,d){y("Assertion failed: "+G(a)+", at: "+[b?G(b):"unknown filename",c,d?G(d):"unknown function"])},ba:function(a,b){return lb(a,b)},a:function(a){return yb(a)},b:function(a){"uncaught_exception"in mb?mb.Ob++:mb.Ob=1;throw a;},R:function(){jb(63);return-1},B:function(a,b,c){Cb=c;try{var d=T(a);switch(b){case 0:var f=Db();return 0>f?-28:R.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Db(),d.flags|=f,0;case 12:return f=Db(),J[f+0>>1]=
2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return jb(28),-1;default:return-28}}catch(h){return"undefined"!==typeof R&&h instanceof R.Cb||y(h),-h.Ib}},da:function(a,b){try{var c=T(a);return Bb(c.path,b)}catch(d){return"undefined"!==typeof R&&d instanceof R.Cb||y(d),-d.Ib}},Z:function(a,b,c){Cb=c;try{var d=T(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=
Db();return K[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Db(),R.Kc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:y("bad ioctl syscall "+b)}}catch(h){return"undefined"!==typeof R&&h instanceof R.Cb||y(h),-h.Ib}},_:function(a,b,c,d,f,h){try{a:{h<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var m=-28;else{if(0!==(d&32)){var p=vc(16384,b);if(!p){m=-48;break a}wc(p,0,b);k=!0}else{var n=R.$b(f);if(!n){m=-8;break a}var q=R.fc(n,C,a,b,h,c,d);p=q.$d;k=q.Bc}Ab[p]={Qd:p,
Pd:b,Bc:k,fd:f,Zd:c,flags:d,offset:h};m=p}}return m}catch(t){return"undefined"!==typeof R&&t instanceof R.Cb||y(t),-t.Ib}},$:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Ab[a];if(d&&b===d.Pd){var f=R.$b(d.fd);if(d.Zd&2){var h=d.flags,k=d.offset,m=C.slice(a,a+b);R.hc(f,m,k,b,h)}Ab[a]=null;d.Bc&&Y(d.Qd)}c=0}return c}catch(p){return"undefined"!==typeof R&&p instanceof R.Cb||y(p),-p.Ib}},C:function(a,b,c){Cb=c;try{var d=G(a),f=Db();return R.open(d,b,f).fd}catch(h){return"undefined"!==typeof R&&
h instanceof R.Cb||y(h),-h.Ib}},aa:function(a,b,c){try{var d=T(a);return R.read(d,E,b,c)}catch(f){return"undefined"!==typeof R&&f instanceof R.Cb||y(f),-f.Ib}},X:function(a){try{return a=G(a),R.rmdir(a),0}catch(b){return"undefined"!==typeof R&&b instanceof R.Cb||y(b),-b.Ib}},ca:function(a,b){try{return a=G(a),Bb(a,b)}catch(c){return"undefined"!==typeof R&&c instanceof R.Cb||y(c),-c.Ib}},Y:function(a){try{return a=G(a),R.unlink(a),0}catch(b){return"undefined"!==typeof R&&b instanceof R.Cb||y(b),-b.Ib}},
M:function(a,b,c,d,f){var h=Eb(c);b=U(b);W(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,m){return m?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var m=E;else if(2===c)m=J;else if(4===c)m=K;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[k>>h])},Zb:null})},L:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(c){var d=X[c].value;Qb(c);return d},toWireType:function(c,d){return Rb(d)},argPackAdvance:8,readValueFromPointer:Sb,
Zb:null})},y:function(a,b,c){c=Eb(c);b=U(b);W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Tb(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Ub(b,c),Zb:null})},F:function(a,b,c,d,f,h){var k=Zb(b,c);a=U(a);f=$b(d,f);Yb(a,function(){dc("Cannot call "+a+" due to unbound types",k)},b-1);Ob(k,function(m){var p=[m[0],null].concat(m.slice(1)),n=m=a,q=f,t=p.length;2>t&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var x=null!==p[1]&&!1,l=!1,r=1;r<p.length;++r)if(null!==p[r]&&void 0===p[r].Zb){l=!0;break}var w="void"!==p[0].name,z="",D="";for(r=0;r<t-2;++r)z+=(0!==r?", ":"")+"arg"+r,D+=(0!==r?", ":"")+"arg"+r+"Wired";n="return function "+Jb(n)+"("+z+") {\nif (arguments.length !== "+(t-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+(t-2)+" args!');\n}\n";l&&(n+="var destructors = [];\n");var Ea=l?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
q=[V,q,h,Wb,p[0],p[1]];x&&(n+="var thisWired = classParam.toWireType("+Ea+", this);\n");for(r=0;r<t-2;++r)n+="var arg"+r+"Wired = argType"+r+".toWireType("+Ea+", arg"+r+"); // "+p[r+2].name+"\n",z.push("argType"+r),q.push(p[r+2]);x&&(D="thisWired"+(0<D.length?", ":"")+D);n+=(w?"var rv = ":"")+"invoker(fn"+(0<D.length?", ":"")+D+");\n";if(l)n+="runDestructors(destructors);\n";else for(r=x?1:2;r<p.length;++r)t=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==p[r].Zb&&(n+=t+"_dtor("+t+"); // "+p[r].name+
"\n",z.push(t+"_dtor"),q.push(p[r].Zb));w&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(n+"}\n");p=Vb(z).apply(null,q);r=b-1;if(!e.hasOwnProperty(m))throw new Nb("Replacing nonexistant public symbol");void 0!==e[m].Vb&&void 0!==r?e[m].Vb[r]=p:(e[m]=p,e[m].xd=r);return[]})},n:function(a,b,c,d,f){function h(n){return n}b=U(b);-1===f&&(f=4294967295);var k=Eb(c);if(0===d){var m=32-8*c;h=function(n){return n<<m>>>m}}var p=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:h,toWireType:function(n,
q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Tb(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+Tb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return p?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:ec(b,k,0!==d),Zb:null})},l:function(a,b,c){function d(h){h>>=2;var k=L;return new f(Ga,k[h+1],k[h])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=U(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Md:!0})},z:function(a,b){b=U(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=L[d>>2];if(c){var h=C[d+4+f],k=0;0!=h&&(k=h,C[d+4+f]=0);var m=d+4;for(h=0;h<=f;++h){var p=d+4+h;if(0==C[p]){m=G(m);if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;m=p+1}}0!=k&&(C[d+4+f]=k)}else{n=Array(f);for(h=0;h<f;++h)n[h]=String.fromCharCode(C[d+4+h]);n=n.join("")}Y(d);
return n},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var h="string"===typeof f;h||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||V("Cannot pass non-string to std::string");var k=(c&&h?function(){return xa(f)}:function(){return f.length})(),m=yb(4+k+1);L[m>>2]=k;if(c&&h)ua(f,C,m+4,k+1);else if(h)for(h=0;h<k;++h){var p=f.charCodeAt(h);255<p&&(Y(m),V("String has UTF-16 code units that do not fit in 8 bits"));C[m+4+h]=p}else for(h=0;h<k;++h)C[m+
4+h]=f[h];null!==d&&d.push(Y,m);return m},argPackAdvance:8,readValueFromPointer:Sb,Zb:function(d){Y(d)}})},s:function(a,b,c){c=U(c);if(2===b){var d=za;var f=Aa;var h=Ba;var k=function(){return Ha};var m=1}else 4===b&&(d=Ca,f=Da,h=Fa,k=function(){return L},m=2);W(a,{name:c,fromWireType:function(p){var n=L[p>>2],q=k(),t=q[p+4+n*b>>m],x=0;0!=t&&(x=t,q[p+4+n*b>>m]=0);var l=p+4;for(t=0;t<=n;++t){var r=p+4+t*b;if(0==q[r>>m]){l=d(l);if(void 0===w)var w=l;else w+=String.fromCharCode(0),w+=l;l=r+b}}0!=x&&
(q[p+4+n*b>>m]=x);Y(p);return w},toWireType:function(p,n){"string"!==typeof n&&V("Cannot pass non-string to C++ string type "+c);var q=h(n),t=yb(4+q+b);L[t>>2]=q>>m;f(n,t+4,q+b);null!==p&&p.push(Y,t);return t},argPackAdvance:8,readValueFromPointer:Sb,Zb:function(p){Y(p)}})},N:function(a,b){b=U(b);W(a,{ue:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},D:Qb,E:function(a){4<a&&(X[a].Sc+=1)},G:function(a,b){var c=Hb[a];void 0===c&&V("_emval_take_value has unknown type "+
bc(a));a=c.readValueFromPointer(b);return Rb(a)},q:function(){y()},S:lb,f:function(a,b){Z(a,b||1);throw"longjmp";},J:function(a,b,c){C.copyWithin(a,b,b+c)},K:function(a){a>>>=0;var b=C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-Ga.byteLength+65535>>>16);Ka(B.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},U:function(a,b){var c=0;kc().forEach(function(d,
f){var h=b+c;f=K[a+4*f>>2]=h;for(h=0;h<d.length;++h)E[f++>>0]=d.charCodeAt(h);E[f>>0]=0;c+=d.length+1});return 0},V:function(a,b){var c=kc();K[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});K[b>>2]=d;return 0},x:function(a){if(!noExitRuntime&&(qa=!0,e.onExit))e.onExit(a);ca(a,new la(a))},t:function(a){try{var b=T(a);R.close(b);return 0}catch(c){return"undefined"!==typeof R&&c instanceof R.Cb||y(c),c.Ib}},T:function(a,b){try{var c=T(a);E[b>>0]=c.tty?2:R.Kb(c.mode)?3:R.ec(c.mode)?7:4;
return 0}catch(d){return"undefined"!==typeof R&&d instanceof R.Cb||y(d),d.Ib}},W:function(a,b,c,d){try{a:{for(var f=T(a),h=a=0;h<c;h++){var k=K[b+(8*h+4)>>2],m=R.read(f,E,K[b+8*h>>2],k,void 0);if(0>m){var p=-1;break a}a+=m;if(m<k)break}p=a}K[d>>2]=p;return 0}catch(n){return"undefined"!==typeof R&&n instanceof R.Cb||y(n),n.Ib}},I:function(a,b,c,d,f){try{var h=T(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;R.Sb(h,a,d);N=[h.position>>>0,(M=h.position,1<=+Sa(M)?0<M?
(Va(+Ua(M/4294967296),4294967295)|0)>>>0:~~+Ta((M-+(~~M>>>0))/4294967296)>>>0:0)];K[f>>2]=N[0];K[f+4>>2]=N[1];h.Hc&&0===a&&0===d&&(h.Hc=null);return 0}catch(k){return"undefined"!==typeof R&&k instanceof R.Cb||y(k),k.Ib}},u:function(a,b,c,d){try{a:{for(var f=T(a),h=a=0;h<c;h++){var k=R.write(f,E,K[b+8*h>>2],K[b+(8*h+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}K[d>>2]=m;return 0}catch(p){return"undefined"!==typeof R&&p instanceof R.Cb||y(p),p.Ib}},c:function(){return na|0},h:xc,p:yc,o:zc,r:Ac,
na:Bc,i:Cc,j:Dc,ma:Ec,m:Fc,oa:Gc,la:Hc,memory:B,fa:function(){return 0},ha:function(){return 0},ga:function(){},w:function(){return 6},ea:function(){},v:function(){},A:function(){},P:function(){},O:function(){},g:hc,H:function(){},ka:function(){},ia:function(){},ja:function(){},d:function(a){na=a|0},Q:function(a,b,c,d){return rc(a,b,c,d)},table:pa,e:function(a,b,c){a|=0;b|=0;c|=0;for(var d=0,f;(d|0)<(c|0);){f=K[b+(d<<3)>>2]|0;if(0==(f|0))break;if((f|0)==(a|0))return K[b+((d<<3)+4)>>2]|0;d=d+1|0}return 0}},
Jc=function(){function a(f){e.asm=f.exports;$a()}function b(f){a(f.instance)}function c(f){return fb().then(function(h){return WebAssembly.instantiate(h,d)}).then(f,function(h){A("failed to asynchronously prepare wasm: "+h);y(h)})}var d={a:Ic};Za();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||cb()||ab("file://")||"function"!==typeof fetch)return c(b);
fetch(bb,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();e.asm=Jc;var gb=e.___wasm_call_ctors=function(){return(gb=e.___wasm_call_ctors=e.asm.pa).apply(null,arguments)},wc=e._memset=function(){return(wc=e._memset=e.asm.qa).apply(null,arguments)};e._epub_open=function(){return(e._epub_open=e.asm.ra).apply(null,arguments)};
e._epub_count=function(){return(e._epub_count=e.asm.sa).apply(null,arguments)};e.__Z12rotate_imageNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi=function(){return(e.__Z12rotate_imageNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi=e.asm.ta).apply(null,arguments)};
var yb=e._malloc=function(){return(yb=e._malloc=e.asm.ua).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.va).apply(null,arguments)},kb=e.___errno_location=function(){return(kb=e.___errno_location=e.asm.wa).apply(null,arguments)},ic=e._realloc=function(){return(ic=e._realloc=e.asm.xa).apply(null,arguments)};e.__Z10epub_imagei=function(){return(e.__Z10epub_imagei=e.asm.ya).apply(null,arguments)};e._analyse=function(){return(e._analyse=e.asm.za).apply(null,arguments)};
e._rotate=function(){return(e._rotate=e.asm.Aa).apply(null,arguments)};e._version=function(){return(e._version=e.asm.Ba).apply(null,arguments)};var Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.Ca).apply(null,arguments)},cc=e.___getTypeName=function(){return(cc=e.___getTypeName=e.asm.Da).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.Ea).apply(null,arguments)};
var vc=e._memalign=function(){return(vc=e._memalign=e.asm.Fa).apply(null,arguments)},Kc=e.dynCall_vi=function(){return(Kc=e.dynCall_vi=e.asm.Ga).apply(null,arguments)},Lc=e.dynCall_vii=function(){return(Lc=e.dynCall_vii=e.asm.Ha).apply(null,arguments)},Mc=e.dynCall_viii=function(){return(Mc=e.dynCall_viii=e.asm.Ia).apply(null,arguments)},Nc=e.dynCall_viiii=function(){return(Nc=e.dynCall_viiii=e.asm.Ja).apply(null,arguments)};
e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.Ka).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.La).apply(null,arguments)};
var Oc=e.dynCall_viiiiiiiii=function(){return(Oc=e.dynCall_viiiiiiiii=e.asm.Ma).apply(null,arguments)},Pc=e.dynCall_viidd=function(){return(Pc=e.dynCall_viidd=e.asm.Na).apply(null,arguments)},Qc=e.dynCall_ii=function(){return(Qc=e.dynCall_ii=e.asm.Oa).apply(null,arguments)},Rc=e.dynCall_iii=function(){return(Rc=e.dynCall_iii=e.asm.Pa).apply(null,arguments)},Sc=e.dynCall_iiii=function(){return(Sc=e.dynCall_iiii=e.asm.Qa).apply(null,arguments)},Tc=e.dynCall_iiiii=function(){return(Tc=e.dynCall_iiiii=
e.asm.Ra).apply(null,arguments)};e.dynCall_iiiiii=function(){return(e.dynCall_iiiiii=e.asm.Sa).apply(null,arguments)};var Uc=e.dynCall_iiiiiiiiii=function(){return(Uc=e.dynCall_iiiiiiiiii=e.asm.Ta).apply(null,arguments)},F=e.stackSave=function(){return(F=e.stackSave=e.asm.Ua).apply(null,arguments)},ta=e.stackAlloc=function(){return(ta=e.stackAlloc=e.asm.Va).apply(null,arguments)},I=e.stackRestore=function(){return(I=e.stackRestore=e.asm.Wa).apply(null,arguments)};
e.dynCall_ji=function(){return(e.dynCall_ji=e.asm.Xa).apply(null,arguments)};e.dynCall_viiiiiiii=function(){return(e.dynCall_viiiiiiii=e.asm.Ya).apply(null,arguments)};e.dynCall_viiiiiii=function(){return(e.dynCall_viiiiiii=e.asm.Za).apply(null,arguments)};e.dynCall_viiiiiiiiii=function(){return(e.dynCall_viiiiiiiiii=e.asm._a).apply(null,arguments)};e.dynCall_viiiiiiiddi=function(){return(e.dynCall_viiiiiiiddi=e.asm.$a).apply(null,arguments)};
e.dynCall_viiiiiiiiiiddi=function(){return(e.dynCall_viiiiiiiiiiddi=e.asm.ab).apply(null,arguments)};e.dynCall_viiid=function(){return(e.dynCall_viiid=e.asm.bb).apply(null,arguments)};e.dynCall_viiiid=function(){return(e.dynCall_viiiid=e.asm.cb).apply(null,arguments)};e.dynCall_viidi=function(){return(e.dynCall_viidi=e.asm.db).apply(null,arguments)};e.dynCall_vidii=function(){return(e.dynCall_vidii=e.asm.eb).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.fb).apply(null,arguments)};
e.dynCall_iiiiiiiii=function(){return(e.dynCall_iiiiiiiii=e.asm.gb).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.hb).apply(null,arguments)};e.dynCall_jiiii=function(){return(e.dynCall_jiiii=e.asm.ib).apply(null,arguments)};e.dynCall_diiii=function(){return(e.dynCall_diiii=e.asm.jb).apply(null,arguments)};e.dynCall_diiiiiiii=function(){return(e.dynCall_diiiiiiii=e.asm.kb).apply(null,arguments)};e.dynCall_fi=function(){return(e.dynCall_fi=e.asm.lb).apply(null,arguments)};
e.dynCall_dii=function(){return(e.dynCall_dii=e.asm.mb).apply(null,arguments)};e.dynCall_diii=function(){return(e.dynCall_diii=e.asm.nb).apply(null,arguments)};e.dynCall_fii=function(){return(e.dynCall_fii=e.asm.ob).apply(null,arguments)};e.dynCall_viij=function(){return(e.dynCall_viij=e.asm.pb).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.qb).apply(null,arguments)};e.dynCall_viiiiiiiiiiii=function(){return(e.dynCall_viiiiiiiiiiii=e.asm.rb).apply(null,arguments)};
e.dynCall_vij=function(){return(e.dynCall_vij=e.asm.sb).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.tb).apply(null,arguments)};e.dynCall_viiiiiiiiidd=function(){return(e.dynCall_viiiiiiiiidd=e.asm.ub).apply(null,arguments)};e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.vb).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.wb).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.xb).apply(null,arguments)};
e.dynCall_iiiiid=function(){return(e.dynCall_iiiiid=e.asm.yb).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.zb).apply(null,arguments)};e.dynCall_iiiiiiii=function(){return(e.dynCall_iiiiiiii=e.asm.Ab).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.Bb).apply(null,arguments)};function Cc(a,b){var c=F();try{Kc(a,b)}catch(d){I(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function xc(a,b){var c=F();try{return Qc(a,b)}catch(d){I(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Fc(a,b,c,d){var f=F();try{Mc(a,b,c,d)}catch(h){I(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function yc(a,b,c){var d=F();try{return Rc(a,b,c)}catch(f){I(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Dc(a,b,c){var d=F();try{Lc(a,b,c)}catch(f){I(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function Ac(a,b,c,d,f){var h=F();try{return Tc(a,b,c,d,f)}catch(k){I(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function zc(a,b,c,d){var f=F();try{return Sc(a,b,c,d)}catch(h){I(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function Gc(a,b,c,d,f){var h=F();try{Nc(a,b,c,d,f)}catch(k){I(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Bc(a,b,c,d,f,h,k,m,p,n){var q=F();try{return Uc(a,b,c,d,f,h,k,m,p,n)}catch(t){I(q);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}
function Ec(a,b,c,d,f){var h=F();try{Pc(a,b,c,d,f)}catch(k){I(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Hc(a,b,c,d,f,h,k,m,p,n){var q=F();try{Oc(a,b,c,d,f,h,k,m,p,n)}catch(t){I(q);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}e.asm=Jc;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(h){return"number"===h});return"string"!==b&&f&&!d?ra(a):function(){return sa(a,b,c,arguments)}};e.FS=R;var Vc;
e.then=function(a){if(Vc)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ya=function Wc(){Vc||Xc();Vc||(Ya=Wc)};
function Xc(){function a(){if(!Vc&&(Vc=!0,e.calledRun=!0,!qa)){e.noFSInit||R.mc.Jc||R.mc();Ma(Oa);R.ld=!1;Ma(Pa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Qa.unshift(b)}Ma(Qa)}}if(!(0<Wa)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ra();Ma(Na);0<Wa||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Xc;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Xc();


  return Module
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    