
var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ha=Object.assign({},f),ia="./this.program",ja=(a,b)=>{throw b;},k="",ka,la;
if(fa){var fs=require("fs"),ma=require("path");k=__dirname+"/";la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!f.thisProgram&&1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ja=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),
_scriptName&&(k=_scriptName),k.startsWith("blob:")?k="":k=k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var oa=f.print||console.log.bind(console),t=f.printErr||console.error.bind(console);Object.assign(f,ha);ha=null;f.thisProgram&&(ia=f.thisProgram);var qa=f.wasmBinary,ra,sa=!1,u,v,ta,ua,x,y,va,wa;
function xa(){var a=ra.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=ta=new Int16Array(a);f.HEAPU8=v=new Uint8Array(a);f.HEAPU16=ua=new Uint16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU32=y=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=wa=new Float64Array(a)}function ya(){var a=za();0==a&&(a+=4);y[a>>2]=34821223;y[a+4>>2]=2310721022;y[0]=1668509029}
function Aa(){if(!sa){var a=za();0==a&&(a+=4);var b=y[a>>2],c=y[a+4>>2];34821223==b&&2310721022==c||Ba(`Stack overflow! Stack cookie has been overwritten at ${"0x"+(a>>>0).toString(16).padStart(8,"0")}, expected hex dwords 0x89BACDFE and 0x2135467, but received ${"0x"+(c>>>0).toString(16).padStart(8,"0")} ${"0x"+(b>>>0).toString(16).padStart(8,"0")}`);1668509029!=y[0]&&Ba("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Ca=[],Da=[],Ea=[];
function Fa(){var a=f.preRun.shift();Ca.unshift(a)}var Ga=0,Ha=null,Ia=null;function Ja(){Ga++;f.monitorRunDependencies?.(Ga)}function Ka(){Ga--;f.monitorRunDependencies?.(Ga);if(0==Ga&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia)){var a=Ia;Ia=null;a()}}function Ba(a){f.onAbort?.(a);a="Aborted("+a+")";t(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var La=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ma;
function Na(a){if(a==Ma&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function Oa(a){return qa?Promise.resolve().then(()=>Na(a)):ka(a).then(b=>new Uint8Array(b),()=>Na(a))}function Pa(a,b,c){return Oa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{t(`failed to asynchronously prepare wasm: ${d}`);Ba(d)})}
function Qa(a,b){var c=Ma;return qa||"function"!=typeof WebAssembly.instantiateStreaming||La(c)||na(c)||fa||"function"!=typeof fetch?Pa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){t(`wasm streaming compile failed: ${e}`);t("falling back to ArrayBuffer instantiation");return Pa(c,a,b)}))}var z,E;class Ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Sa=a=>{for(;0<a.length;)a.shift()(f)},Ta=f.noExitRuntime||!0,Ua="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ua)return Ua.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class Va{constructor(a){this.R=a-24}U(a,b){y[this.R+16>>2]=0;y[this.R+4>>2]=a;y[this.R+8>>2]=b}}
var Wa=0,Xa=0,G=()=>{var a=x[+Ya>>2];Ya+=4;return a},Za=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},I=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},$a=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.substr(0,b.length-1);return a+b},ab=a=>{if("/"===a)return"/";a=I(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},bb=(a,b)=>I(a+"/"+b),cb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(fa)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Ba("initRandomDevice")},db=a=>(db=cb())(a),eb=(...a)=>{for(var b=
"",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:J.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Za(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},fb=(a,b)=>{function c(h){for(var l=0;l<h.length&&""===h[l];l++);for(var n=h.length-1;0<=n&&""===h[n];n--);return l>n?[]:h.slice(l,n-l+1)}a=eb(a).substr(1);b=eb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),
e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},gb=[],hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;
b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function jb(a){var b=Array(hb(a)+1);a=ib(a,b,0,b.length);b.length=a;return b}var kb=[];function lb(a,b){kb[a]={input:[],output:[],J:b};mb(a,nb)}
var nb={open(a){var b=kb[a.node.rdev];if(!b)throw new J.g(43);a.tty=b;a.seekable=!1},close(a){a.tty.J.fsync(a.tty)},fsync(a){a.tty.J.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.J.ma)throw new J.g(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.J.ma(a.tty)}catch(l){throw new J.g(29);}if(void 0===h&&0===e)throw new J.g(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.J.ea)throw new J.g(60);try{for(var e=0;e<d;e++)a.tty.J.ea(a.tty,
b[c+e])}catch(g){throw new J.g(29);}d&&(a.node.timestamp=Date.now());return e}},ob={ma(){a:{if(!gb.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}gb=jb(a)}a=gb.shift()}return a},ea(a,b){null===b||10===b?(oa(F(a.output)),
a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(F(a.output)),a.output=[])},Ha(){return{Ua:25856,Wa:5,Ta:191,Va:35387,Sa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ia(){return 0},Ja(){return[24,80]}},pb={ea(a,b){null===b||10===b?(t(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(t(F(a.output)),a.output=[])}},rb=a=>{a=65536*Math.ceil(a/65536);var b=qb(65536,a);b&&v.fill(0,b,b+a);return b};
function sb(a,b){var c=a.j?a.j.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.j,a.j=new Uint8Array(b),0<a.l&&a.j.set(c.subarray(0,a.l),0))}
var K={F:null,m(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||J.isFIFO(c))throw new J.g(63);K.F||(K.F={dir:{node:{C:K.h.C,s:K.h.s,lookup:K.h.lookup,I:K.h.I,rename:K.h.rename,unlink:K.h.unlink,rmdir:K.h.rmdir,readdir:K.h.readdir,symlink:K.h.symlink},stream:{v:K.i.v}},file:{node:{C:K.h.C,s:K.h.s},stream:{v:K.i.v,read:K.i.read,write:K.i.write,S:K.i.S,N:K.i.N,P:K.i.P}},link:{node:{C:K.h.C,s:K.h.s,readlink:K.h.readlink},stream:{}},ia:{node:{C:K.h.C,s:K.h.s},stream:J.Ba}});
c=J.createNode(a,b,c,d);L(c.mode)?(c.h=K.F.dir.node,c.i=K.F.dir.stream,c.j={}):J.isFile(c.mode)?(c.h=K.F.file.node,c.i=K.F.file.stream,c.l=0,c.j=null):40960===(c.mode&61440)?(c.h=K.F.link.node,c.i=K.F.link.stream):8192===(c.mode&61440)&&(c.h=K.F.ia.node,c.i=K.F.ia.stream);c.timestamp=Date.now();a&&(a.j[b]=c,a.timestamp=c.timestamp);return c},gb(a){return a.j?a.j.subarray?a.j.subarray(0,a.l):new Uint8Array(a.j):new Uint8Array(0)},h:{C(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:J.isFile(a.mode)?b.size=a.l:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.za=4096;b.blocks=Math.ceil(b.size/b.za);return b},s(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.l!=b))if(0==b)a.j=null,a.l=0;else{var c=a.j;a.j=new Uint8Array(b);c&&a.j.set(c.subarray(0,
Math.min(b,a.l)));a.l=b}},lookup(){throw K.la;},I(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){if(L(a.mode)){try{var d=N(b,c)}catch(g){}if(d)for(var e in d.j)throw new J.g(55);}delete a.parent.j[a.name];a.parent.timestamp=Date.now();a.name=c;b.j[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.j[b];a.timestamp=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.j)throw new J.g(55);delete a.j[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.j))b.push(c);
return b},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J.g(28);return a.link}},i:{read(a,b,c,d,e){var g=a.node.j;if(e>=a.node.l)return 0;a=Math.min(a.node.l-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.j||a.j.subarray)){if(g)return a.j=b.subarray(c,c+d),a.l=d;if(0===a.l&&
0===e)return a.j=b.slice(c,c+d),a.l=d;if(e+d<=a.l)return a.j.set(b.subarray(c,c+d),e),d}sb(a,e+d);if(a.j.subarray&&b.subarray)a.j.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.j[e+g]=b[c+g];a.l=Math.max(a.l,e+d);return d},v(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.l);if(0>b)throw new J.g(28);return b},S(a,b,c){sb(a.node,b+c);a.node.l=Math.max(a.node.l,b+c)},N(a,b,c,d,e){if(!J.isFile(a.node.mode))throw new J.g(43);a=a.node.j;if(e&2||!a||a.buffer!==u.buffer){d=!0;e=rb(b);
if(!e)throw new J.g(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{R:e,ga:d}},P(a,b,c,d){K.i.write(a,b,0,d,c,!1);return 0}}},tb=(a,b,c)=>{var d=`al ${a}`;ka(a).then(e=>{b(new Uint8Array(e));d&&Ka()},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ja()},ub=f.preloadPlugins||[],vb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.U();var e=!1;ub.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,
b,c,d),e=!0)});return e},wb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};function mb(a,b){J.ka[a]={i:b}}function L(a){return 16384===(a&61440)}function N(a,b){var c=L(a.mode)?(c=xb(a,"x"))?c:a.h.lookup?0:2:54;if(c)throw new J.g(c);for(c=J.D[yb(a.id,b)];c;c=c.O){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return J.lookup(a,b)}
function O(a,b={}){a=eb(a);if(!a)return{path:"",node:null};b=Object.assign({W:!0,fa:0},b);if(8<b.fa)throw new J.g(32);a=a.split("/").filter(h=>!!h);for(var c=J.root,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=N(c,a[e]);d=I(d+"/"+a[e]);c.A&&(!g||g&&b.W)&&(c=c.A.root);if(!g||b.u)for(g=0;40960===(c.mode&61440);)if(c=J.readlink(d),d=eb($a(d),c),c=O(d,{fa:b.fa+1}).node,40<g++)throw new J.g(32);}return{path:d,node:c}}
function zb(a){for(var b;;){if(J.oa(a))return a=a.m.sa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function yb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%J.D.length}function Ab(a){var b=yb(a.parent.id,a.name);a.O=J.D[b];J.D[b]=a}function Bb(a){var b=yb(a.parent.id,a.name);if(J.D[b]===a)J.D[b]=a.O;else for(b=J.D[b];b;){if(b.O===a){b.O=a.O;break}b=b.O}}function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function xb(a,b){if(J.na)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Db(a,b){try{return N(a,b),20}catch(c){}return xb(a,"wx")}function Eb(a,b,c){try{var d=N(a,b)}catch(e){return e.o}if(a=xb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(J.oa(d)||zb(d)===J.cwd())return 10}else if(L(d.mode))return 31;return 0}function P(a){a=J.Fa(a);if(!a)throw new J.g(8);return a}
function Fb(a,b=-1){a=Object.assign(new J.xa,a);if(-1==b)a:{for(b=0;b<=J.ya;b++)if(!J.streams[b])break a;throw new J.g(33);}a.fd=b;return J.streams[b]=a}function Gb(a,b=-1){a=Fb(a,b);a.i?.$a?.(a);return a}function Hb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.T)}return b}function Ib(a,b,c){"undefined"==typeof c&&(c=b,b=438);return J.I(a,b|8192,c)}function Jb(a,b,c,d){a="string"==typeof a?a:zb(a);b=I(a+"/"+b);return J.create(b,wb(c,d))}
function Kb(a){if(!(a.Ka||a.La||a.link||a.j)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.j=la(a.url),a.l=a.j.length}catch(b){throw new J.g(29);}}}
var J={root:null,T:[],ka:{},streams:[],da:1,D:null,ja:"/",$:!1,na:!0,g:class{name="ErrnoError";constructor(a){this.o=a}},Da:null,V:0,ta:{},xa:class{H={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.H.flags}set flags(a){this.H.flags=a}get position(){return this.H.position}set position(a){this.H.position=a}},wa:class{h={};i={};A=null;constructor(a,b,c,d){a||=this;this.parent=a;this.m=a.m;this.id=J.da++;this.name=b;this.mode=c;this.rdev=d}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get La(){return L(this.mode)}get Ka(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new J.wa(a,b,c,d);Ab(a);return a},oa(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},ya:4096,Fa:a=>J.streams[a],Ba:{open(a){a.i=J.Ea(a.node.rdev).i;a.i.open?.(a)},v(){throw new J.g(70);
}},ba:a=>a>>8,jb:a=>a&255,M:(a,b)=>a<<8|b,Ea:a=>J.ka[a],va(a,b){function c(h){J.V--;return b(h)}function d(h){if(h){if(!d.Ca)return d.Ca=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);J.V++;1<J.V&&t(`warning: ${J.V} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Hb(J.root.m),g=0;e.forEach(h=>{if(!h.type.va)return d(null);h.type.va(h,a,d)})},m(a,b,c){var d="/"===c;if(d&&J.root)throw new J.g(10);if(!d&&c){var e=O(c,{W:!1});c=e.path;e=e.node;if(e.A)throw new J.g(10);
if(!L(e.mode))throw new J.g(54);}b={type:a,Na:b,sa:c,T:[]};a=a.m(b);a.m=b;b.root=a;d?J.root=a:e&&(e.A=b,e.m&&e.m.T.push(b));return a},nb(a){a=O(a,{W:!1});if(!a.node.A)throw new J.g(28);a=a.node;var b=a.A,c=Hb(b);Object.keys(J.D).forEach(d=>{for(d=J.D[d];d;){var e=d.O;c.includes(d.m)&&Bb(d);d=e}});a.A=null;a.m.T.splice(a.m.T.indexOf(b),1)},lookup(a,b){return a.h.lookup(a,b)},I(a,b,c){var d=O(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new J.g(28);var e=Db(d,a);if(e)throw new J.g(e);
if(!d.h.I)throw new J.g(63);return d.h.I(d,a,b,c)},ua(a){var b={Ra:4096,cb:4096,blocks:1E6,Qa:5E5,Pa:5E5,files:J.da,ab:J.da-1,eb:42,flags:2,lb:255};a=O(a,{u:!0}).node;a?.h.ua&&Object.assign(b,a.h.ua(a.m.Na.root));return b},create(a,b=438){return J.I(a,b&4095|32768,0)},mkdir(a,b=511){return J.I(a,b&1023|16384,0)},kb(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{J.mkdir(c,b)}catch(e){if(20!=e.o)throw e;}}},symlink(a,b){if(!eb(a))throw new J.g(44);var c=O(b,{parent:!0}).node;
if(!c)throw new J.g(44);b=ab(b);var d=Db(c,b);if(d)throw new J.g(d);if(!c.h.symlink)throw new J.g(63);return c.h.symlink(c,b,a)},rename(a,b){var c=$a(a),d=$a(b),e=ab(a),g=ab(b);var h=O(a,{parent:!0});var l=h.node;h=O(b,{parent:!0});h=h.node;if(!l||!h)throw new J.g(44);if(l.m!==h.m)throw new J.g(75);var n=N(l,e);a=fb(a,d);if("."!==a.charAt(0))throw new J.g(28);a=fb(b,c);if("."!==a.charAt(0))throw new J.g(55);try{var m=N(h,g)}catch(r){}if(n!==m){b=L(n.mode);if(e=Eb(l,e,b))throw new J.g(e);if(e=m?Eb(h,
g,b):Db(h,g))throw new J.g(e);if(!l.h.rename)throw new J.g(63);if(n.A||m&&m.A)throw new J.g(10);if(h!==l&&(e=xb(l,"w")))throw new J.g(e);Bb(n);try{l.h.rename(n,h,g),n.parent=h}catch(r){throw r;}finally{Ab(n)}}},rmdir(a){var b=O(a,{parent:!0}).node;a=ab(a);var c=N(b,a),d=Eb(b,a,!0);if(d)throw new J.g(d);if(!b.h.rmdir)throw new J.g(63);if(c.A)throw new J.g(10);b.h.rmdir(b,a);Bb(c)},readdir(a){a=O(a,{u:!0}).node;if(!a.h.readdir)throw new J.g(54);return a.h.readdir(a)},unlink(a){var b=O(a,{parent:!0}).node;
if(!b)throw new J.g(44);a=ab(a);var c=N(b,a),d=Eb(b,a,!1);if(d)throw new J.g(d);if(!b.h.unlink)throw new J.g(63);if(c.A)throw new J.g(10);b.h.unlink(b,a);Bb(c)},readlink(a){a=O(a).node;if(!a)throw new J.g(44);if(!a.h.readlink)throw new J.g(28);return a.h.readlink(a)},stat(a,b){a=O(a,{u:!b}).node;if(!a)throw new J.g(44);if(!a.h.C)throw new J.g(63);return a.h.C(a)},lstat(a){return J.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?O(a,{u:!c}).node:a;if(!a.h.s)throw new J.g(63);a.h.s(a,{mode:b&4095|a.mode&
-4096,timestamp:Date.now()})},lchmod(a,b){J.chmod(a,b,!0)},fchmod(a,b){a=P(a);J.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?O(a,{u:!d}).node:a;if(!a.h.s)throw new J.g(63);a.h.s(a,{timestamp:Date.now()})},lchown(a,b,c){J.chown(a,b,c,!0)},fchown(a,b,c){a=P(a);J.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new J.g(28);a="string"==typeof a?O(a,{u:!0}).node:a;if(!a.h.s)throw new J.g(63);if(L(a.mode))throw new J.g(31);if(!J.isFile(a.mode))throw new J.g(28);var c=xb(a,"w");if(c)throw new J.g(c);
a.h.s(a,{size:b,timestamp:Date.now()})},fb(a,b){a=P(a);if(0===(a.flags&2097155))throw new J.g(28);J.truncate(a.node,b)},ob(a,b,c){a=O(a,{u:!0}).node;a.h.s(a,{timestamp:Math.max(b,c)})},open(a,b,c=438){if(""===a)throw new J.g(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)var e=a;else{a=I(a);try{e=O(a,{u:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&
128)throw new J.g(20);}else e=J.I(a,c,0),d=!0;if(!e)throw new J.g(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!L(e.mode))throw new J.g(54);if(!d&&(c=e?40960===(e.mode&61440)?32:L(e.mode)&&("r"!==Cb(b)||b&512)?31:xb(e,Cb(b)):44))throw new J.g(c);b&512&&!d&&J.truncate(e,0);b&=-131713;e=Fb({node:e,path:zb(e),flags:b,seekable:!0,position:0,i:e.i,Oa:[],error:!1});e.i.open&&e.i.open(e);!f.logReadFiles||b&1||a in J.ta||(J.ta[a]=1);return e},close(a){if(null===a.fd)throw new J.g(8);a.X&&(a.X=null);try{a.i.close&&
a.i.close(a)}catch(b){throw b;}finally{J.streams[a.fd]=null}a.fd=null},v(a,b,c){if(null===a.fd)throw new J.g(8);if(!a.seekable||!a.i.v)throw new J.g(70);if(0!=c&&1!=c&&2!=c)throw new J.g(28);a.position=a.i.v(a,b,c);a.Oa=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new J.g(28);if(null===a.fd)throw new J.g(8);if(1===(a.flags&2097155))throw new J.g(8);if(L(a.node.mode))throw new J.g(31);if(!a.i.read)throw new J.g(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J.g(70);
b=a.i.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new J.g(28);if(null===a.fd)throw new J.g(8);if(0===(a.flags&2097155))throw new J.g(8);if(L(a.node.mode))throw new J.g(31);if(!a.i.write)throw new J.g(28);a.seekable&&a.flags&1024&&J.v(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new J.g(70);b=a.i.write(a,b,c,d,e,g);h||(a.position+=b);return b},S(a,b,c){if(null===a.fd)throw new J.g(8);if(0>b||0>=c)throw new J.g(28);if(0===(a.flags&
2097155))throw new J.g(8);if(!J.isFile(a.node.mode)&&!L(a.node.mode))throw new J.g(43);if(!a.i.S)throw new J.g(138);a.i.S(a,b,c)},N(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new J.g(2);if(1===(a.flags&2097155))throw new J.g(2);if(!a.i.N)throw new J.g(43);if(!b)throw new J.g(28);return a.i.N(a,b,c,d,e)},P(a,b,c,d,e){return a.i.P?a.i.P(a,b,c,d,e):0},aa(a,b,c){if(!a.i.aa)throw new J.g(59);return a.i.aa(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";
if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=J.open(a,b.flags);a=J.stat(a).size;var e=new Uint8Array(a);J.read(d,e,0,a,0);"utf8"===b.encoding?c=F(e):"binary"===b.encoding&&(c=e);J.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=J.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(hb(b)+1);b=ib(b,d,0,d.length);J.write(a,d,0,b,void 0,c.Aa)}else if(ArrayBuffer.isView(b))J.write(a,b,0,b.byteLength,void 0,c.Aa);
else throw Error("Unsupported data type");J.close(a)},cwd:()=>J.ja,chdir(a){a=O(a,{u:!0});if(null===a.node)throw new J.g(44);if(!L(a.node.mode))throw new J.g(54);var b=xb(a.node,"x");if(b)throw new J.g(b);J.ja=a.path},U(a,b,c){J.$=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?J.L("/dev","stdin",a):J.symlink("/dev/tty","/dev/stdin");b?J.L("/dev","stdout",null,b):J.symlink("/dev/tty","/dev/stdout");c?J.L("/dev","stderr",null,c):J.symlink("/dev/tty1","/dev/stderr");J.open("/dev/stdin",0);J.open("/dev/stdout",
1);J.open("/dev/stderr",1)},mb(){J.$=!1;for(var a=0;a<J.streams.length;a++){var b=J.streams[a];b&&J.close(b)}},bb(a,b){try{var c=O(a,{u:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=O(a,{parent:!0}),ab(a),c=O(a,{u:!b}),d=!0,e=c.node}catch(g){}return d?e:null},Ya(a,b){a="string"==typeof a?a:zb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=I(a+"/"+c);try{J.mkdir(d)}catch(e){}a=d}}return d},L(a,b,c,d){a=bb("string"==typeof a?a:zb(a),b);b=wb(!!c,!!d);var e;(e=J.L).ba??(e.ba=64);
e=J.M(J.L.ba++,0);mb(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,l,n){for(var m=0,r=0;r<n;r++){try{var p=c()}catch(q){throw new J.g(29);}if(void 0===p&&0===m)throw new J.g(6);if(null===p||void 0===p)break;m++;h[l+r]=p}m&&(g.node.timestamp=Date.now());return m},write(g,h,l,n){for(var m=0;m<n;m++)try{d(h[l+m])}catch(r){throw new J.g(29);}n&&(g.node.timestamp=Date.now());return m}});return Ib(a,b,e)},Xa(a,b,c,d,e){function g(p,q,B,C,A){p=p.node.j;if(A>=p.length)return 0;C=Math.min(p.length-
A,C);if(p.slice)for(var w=0;w<C;w++)q[B+w]=p[A+w];else for(w=0;w<C;w++)q[B+w]=p.get(A+w);return C}class h{Z=!1;H=[];Y=void 0;qa=0;pa=0;get(p){if(!(p>this.length-1||0>p)){var q=p%this.chunkSize;return this.Y(p/this.chunkSize|0)[q]}}Ma(p){this.Y=p}ra(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),B,C=(B=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===B;p=(B=p.getResponseHeader("Content-Encoding"))&&"gzip"===B;var A=1048576;C||(A=q);var w=this;w.Ma(H=>{var D=H*A,S=(H+1)*A-1;S=Math.min(S,q-1);if("undefined"==typeof w.H[H]){var pa=w.H;if(D>S)throw Error("invalid range ("+D+", "+S+") or no bytes requested!");if(S>q-1)throw Error("only "+q+" bytes available! programmer error!");var M=new XMLHttpRequest;M.open("GET",c,!1);q!==A&&M.setRequestHeader("Range","bytes="+D+"-"+S);M.responseType="arraybuffer";M.overrideMimeType&&M.overrideMimeType("text/plain; charset=x-user-defined");
M.send(null);if(!(200<=M.status&&300>M.status||304===M.status))throw Error("Couldn't load "+c+". Status: "+M.status);D=void 0!==M.response?new Uint8Array(M.response||[]):jb(M.responseText||"");pa[H]=D}if("undefined"==typeof w.H[H])throw Error("doXHR failed!");return w.H[H]});if(p||!q)A=q=1,A=q=this.Y(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.qa=q;this.pa=A;this.Z=!0}get length(){this.Z||this.ra();return this.qa}get chunkSize(){this.Z||this.ra();
return this.pa}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new h;var n=void 0}else n=c,l=void 0;var m=Jb(a,b,d,e);l?m.j=l:n&&(m.j=null,m.url=n);Object.defineProperties(m,{l:{get:function(){return this.j.length}}});var r={};Object.keys(m.i).forEach(p=>{var q=m.i[p];r[p]=(...B)=>{Kb(m);return q(...B)}});r.read=(p,q,B,C,A)=>{Kb(m);return g(p,q,B,C,A)};r.N=(p,q,B)=>{Kb(m);
var C=rb(q);if(!C)throw new J.g(48);g(p,u,C,q,B);return{R:C,ga:!0}};m.i=r;return m}};function Lb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?J.cwd():P(a).path;if(0==b.length){if(!c)throw new J.g(44);return a}return I(a+"/"+b)}
function Mb(a,b,c){a=a(b);x[c>>2]=a.dev;x[c+4>>2]=a.mode;y[c+8>>2]=a.nlink;x[c+12>>2]=a.uid;x[c+16>>2]=a.gid;x[c+20>>2]=a.rdev;E=[a.size>>>0,(z=a.size,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];x[c+24>>2]=E[0];x[c+28>>2]=E[1];x[c+32>>2]=4096;x[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();E=[Math.floor(b/1E3)>>>0,(z=Math.floor(b/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>
0))/4294967296)>>>0:0)];x[c+40>>2]=E[0];x[c+44>>2]=E[1];y[c+48>>2]=b%1E3*1E6;E=[Math.floor(d/1E3)>>>0,(z=Math.floor(d/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];x[c+56>>2]=E[0];x[c+60>>2]=E[1];y[c+64>>2]=d%1E3*1E6;E=[Math.floor(e/1E3)>>>0,(z=Math.floor(e/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];x[c+72>>2]=E[0];x[c+76>>2]=E[1];y[c+80>>2]=e%1E3*1E6;E=[a.ino>>>0,(z=a.ino,1<=+Math.abs(z)?
0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];x[c+88>>2]=E[0];x[c+92>>2]=E[1];return 0}
var Ya=void 0,Nb,Q=a=>{for(var b="";v[a];)b+=Nb[v[a++]];return b},Ob={},Pb={},Qb={},R,Rb=a=>{throw new R(a);},Sb,Tb=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new Sb("Mismatched type converter count");for(var n=0;n<d.length;++n)T(d[n],l[n])}var d=[];d.forEach(l=>Qb[l]=a);var e=Array(a.length),g=[],h=0;a.forEach((l,n)=>{Pb.hasOwnProperty(l)?e[n]=Pb[l]:(g.push(l),Ob.hasOwnProperty(l)||(Ob[l]=[]),Ob[l].push(()=>{e[n]=Pb[l];++h;h===g.length&&c(e)}))});0===g.length&&c(e)};
function Ub(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(Pb.hasOwnProperty(a)){if(c.Ga)return;throw new R(`Cannot register type '${d}' twice`);}Pb[a]=b;delete Qb[a];Ob.hasOwnProperty(a)&&(b=Ob[a],delete Ob[a],b.forEach(e=>e()))}function T(a,b,c={}){return Ub(a,b,c)}var Vb=[],Wb=[],Xb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Vb.pop()||Wb.length;Wb[b]=a;Wb[b+1]=1;return b}};
function Yb(a){return this.fromWireType(y[a>>2])}
var Zb={name:"emscripten::val",fromWireType:a=>{if(!a)throw new R("Cannot use deleted val. handle = "+a);var b=Wb[a];9<a&&0===--Wb[a+1]&&(Wb[a]=void 0,Vb.push(a));return b},toWireType:(a,b)=>Xb(b),K:8,readValueFromPointer:Yb,G:null},$b=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(va[c>>2])};case 8:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ac=(a,b)=>Object.defineProperty(b,"name",{value:a}),bc=a=>
{for(;a.length;){var b=a.pop();a.pop()(b)}};function cc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].G)return!0;return!1}function dc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ac(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ec(){var a=fc,b=/^(invoke_.*|__asyncjs__.*)$/;for(let [c,d]of Object.entries(a))"function"==typeof d&&(d.hb||b.test(c))&&(a[c]=d=new WebAssembly.Suspending(d))}function gc(){var a=U,b=/^(_epub_image|_rotate_image|main|__main_argc_argv)$/;hc=new Set;var c={};for(let [d,e]of Object.entries(a))"function"==typeof e?(b.test(d)&&(hc.add(e),e=WebAssembly.promising(e)),c[d]=(...g)=>e(...g)):c[d]=e;return c}
var hc=null,ic=(a,b)=>{if(void 0===f[a].B){var c=f[a];f[a]=function(...d){if(!f[a].B.hasOwnProperty(d.length))throw new R(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].B})!`);return f[a].B[d.length].apply(this,d)};f[a].B=[];f[a].B[c.ha]=c}},jc=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].B&&void 0!==f[a].B[c])throw new R(`Cannot register public name '${a}' twice`);ic(a,a);if(f[a].B.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].B[c]=b}else f[a]=b,f[a].ha=c},kc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(y[b+4*d>>2]);return c},lc=[],mc,V=a=>{var b=lc[a];b||(a>=lc.length&&(lc.length=a+1),lc[a]=b=mc.get(a),hc?.has(b)&&(lc[a]=b=WebAssembly.promising(b)));return b},nc=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=V(b)(...c);return b},oc=(a,b)=>(...c)=>nc(a,b,c),pc=(a,b)=>{a=Q(a);var c=a.includes("j")?oc(a,b):V(b);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${a}: ${b}`);
return c},qc,sc=a=>{a=rc(a);var b=Q(a);W(a);return b},tc=(a,b)=>{function c(g){e[g]||Pb[g]||(Qb[g]?Qb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new qc(`${a}: `+d.map(sc).join([", "]));},uc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},vc=(a,b,c)=>{switch(b){case 1:return c?d=>u[d]:d=>v[d];case 2:return c?d=>ta[d>>1]:d=>ua[d>>1];case 4:return c?d=>x[d>>2]:d=>y[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},wc="undefined"!=
typeof TextDecoder?new TextDecoder("utf-16le"):void 0,xc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ua[c];)++c;c<<=1;if(32<c-a&&wc)return wc.decode(v.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ta[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},yc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ta[b>>1]=a.charCodeAt(e),b+=2;ta[b>>1]=0;return b-d},zc=a=>2*a.length,Ac=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=x[a+4*c>>2];if(0==
e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Bc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}x[b>>2]=g;b+=4;if(b+4>c)break}x[b>>2]=0;return b-d},Cc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Dc=[0,31,60,91,121,152,182,213,244,274,305,335],
Ec=[0,31,59,90,120,151,181,212,243,273,304,334],Fc=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,Gc={},Ic=()=>{if(!Hc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in Gc)void 0===Gc[b]?delete a[b]:a[b]=Gc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hc=c}return Hc},Hc,Kc=(a,b,c,d,e)=>{function g(p){0!==n&&X(n);
return"string"===b?p?F(v,p):"":"boolean"===b?!!p:p}var h={string:p=>{var q=0;if(null!==p&&void 0!==p&&0!==p){q=hb(p)+1;var B=Jc(q);ib(p,v,B,q);q=B}return q},array:p=>{var q=Jc(p.length);u.set(p,q);return q}};a=f["_"+a];var l=[],n=0;if(d)for(var m=0;m<d.length;m++){var r=h[c[m]];r?(0===n&&(n=Y()),l[m]=r(d[m])):l[m]=d[m]}c=a(...l);return e?.async?c.then(g):c=g(c)};
J.Za=(a,b,c,d,e,g,h,l,n,m)=>{function r(q){function B(C){m?.();if(!l){var A=a,w=b;A&&(A="string"==typeof A?A:zb(A),w=b?I(A+"/"+b):A);A=wb(d,e);w=J.create(w,A);if(C){if("string"==typeof C){for(var H=Array(C.length),D=0,S=C.length;D<S;++D)H[D]=C.charCodeAt(D);C=H}J.chmod(w,A|146);H=J.open(w,577);J.write(H,C,0,C.length,0,n);J.close(H);J.chmod(w,A)}}g?.();Ka()}vb(q,p,B,()=>{h?.();Ka()})||B(q)}var p=b?eb(I(a+"/"+b)):a;Ja();"string"==typeof c?tb(c,r,h):r(c)};J.D=Array(4096);J.m(K,{},"/");J.mkdir("/tmp");
J.mkdir("/home");J.mkdir("/home/web_user");(function(){J.mkdir("/dev");mb(J.M(1,3),{read:()=>0,write:(d,e,g,h)=>h,v:()=>0});Ib("/dev/null",J.M(1,3));lb(J.M(5,0),ob);lb(J.M(6,0),pb);Ib("/dev/tty",J.M(5,0));Ib("/dev/tty1",J.M(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=db(a).byteLength);return a[--b]};J.L("/dev","random",c);J.L("/dev","urandom",c);J.mkdir("/dev/shm");J.mkdir("/dev/shm/tmp")})();
(function(){J.mkdir("/proc");var a=J.mkdir("/proc/self");J.mkdir("/proc/self/fd");J.m({m(){var b=J.createNode(a,"fd",16895,73);b.h={lookup(c,d){var e=P(+d);c={parent:null,m:{sa:"fake"},h:{readlink:()=>e.path}};return c.parent=c}};return b}},{},"/proc/self/fd")})();J.Da={MEMFS:K};K.la=new J.g(44);K.la.stack="<generic error, no stack>";for(var Lc=Array(256),Mc=0;256>Mc;++Mc)Lc[Mc]=String.fromCharCode(Mc);Nb=Lc;R=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Sb=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Wb.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>Wb.length/2-5-Vb.length;
qc=f.UnboundTypeError=((a,b)=>{var c=ac(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var fc={__assert_fail:(a,b,c,d)=>Ba(`Assertion failed: ${a?F(v,a):""}, at: `+[b?b?F(v,b):"":"unknown filename",c,d?d?F(v,d):"":"unknown function"]),__cxa_throw:(a,b,c)=>{(new Va(a)).U(b,c);Wa=a;Xa++;throw Wa;},__syscall_fcntl64:function(a,b,c){Ya=c;try{var d=P(a);switch(b){case 0:var e=G();if(0>e)break;for(;J.streams[e];)e++;return Gb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=G(),d.flags|=e,0;case 12:return e=G(),ta[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==
typeof J||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_fstat64:function(a,b){try{var c=P(a);return Mb(J.stat,c.path,b)}catch(d){if("undefined"==typeof J||"ErrnoError"!==d.name)throw d;return-d.o}},__syscall_ioctl:function(a,b,c){Ya=c;try{var d=P(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.J.Ha){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=G();x[e>>2]=25856;x[e+4>>2]=5;x[e+8>>2]=191;x[e+12>>2]=35387;for(var g=0;32>
g;g++)u[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.J.Ia)for(e=G(),a=[],g=0;32>g;g++)a.push(u[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=G();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return e=G(),J.aa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.J.Ja&&(g=[24,80],e=G(),ta[e>>1]=g[0],ta[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==
typeof J||"ErrnoError"!==h.name)throw h;return-h.o}},__syscall_newfstatat:function(a,b,c,d){try{b=b?F(v,b):"";var e=d&256;b=Lb(a,b,d&4096);return Mb(e?J.lstat:J.stat,b,c)}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_openat:function(a,b,c,d){Ya=d;try{b=b?F(v,b):"";b=Lb(a,b);var e=d?G():0;return J.open(b,c,e).fd}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_renameat:function(a,b,c,d){try{return b=b?F(v,b):"",d=d?F(v,
d):"",b=Lb(a,b),d=Lb(c,d),J.rename(b,d),0}catch(e){if("undefined"==typeof J||"ErrnoError"!==e.name)throw e;return-e.o}},__syscall_rmdir:function(a){try{return a=a?F(v,a):"",J.rmdir(a),0}catch(b){if("undefined"==typeof J||"ErrnoError"!==b.name)throw b;return-b.o}},__syscall_stat64:function(a,b){try{return a=a?F(v,a):"",Mb(J.stat,a,b)}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return-c.o}},__syscall_unlinkat:function(a,b,c){try{return b=b?F(v,b):"",b=Lb(a,b),0===c?J.unlink(b):
512===c?J.rmdir(b):Ba("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof J||"ErrnoError"!==d.name)throw d;return-d.o}},_abort_js:()=>Ba(""),_embind_register_bigint:()=>{},_embind_register_bool:(a,b,c,d)=>{b=Q(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},K:8,readValueFromPointer:function(e){return this.fromWireType(v[e])},G:null})},_embind_register_emval:a=>T(a,Zb),_embind_register_float:(a,b,c)=>{b=Q(b);T(a,{name:b,fromWireType:d=>d,
toWireType:(d,e)=>e,K:8,readValueFromPointer:$b(b,c),G:null})},_embind_register_function:(a,b,c,d,e,g,h)=>{var l=kc(b,c);a=Q(a);a=uc(a);e=pc(d,e);jc(a,function(){tc(`Cannot call ${a} due to unbound types`,l)},b-1);Tb(l,n=>{var m=[n[0],null].concat(n.slice(1));n=a;var r=a;var p=e,q=m.length;if(2>q)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");h&&(p=WebAssembly.promising(p));var B=null!==m[1]&&!1,C=cc(m),A="void"!==m[0].name;p=[r,Rb,p,g,bc,m[0],m[1]];
for(var w=0;w<q-2;++w)p.push(m[w+2]);if(!C)for(w=B?1:2;w<m.length;++w)null!==m[w].G&&p.push(m[w].G);C=cc(m);var H=m.length-2,D=[];w=["fn"];B&&w.push("thisWired");for(q=0;q<H;++q)D.push(`arg${q}`),w.push(`arg${q}Wired`);D=D.join(",");w=w.join(",");D=`return function (${D}) {\n`;C&&(D+="var destructors = [];\n");var S=C?"destructors":"null",pa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");B&&(D+=`var thisWired = classParam['toWireType'](${S}, this);\n`);for(q=
0;q<H;++q)D+=`var arg${q}Wired = argType${q}['toWireType'](${S}, arg${q});\n`,pa.push(`argType${q}`);H=A?"rv":"";D=D+((A||h?"var rv = ":"")+`invoker(${w});\n`)+`function onDone(${H}) {\n`;if(C)D+="runDestructors(destructors);\n";else for(q=B?1:2;q<m.length;++q)B=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==m[q].G&&(D+=`${B}_dtor(${B});\n`,pa.push(`${B}_dtor`));A&&(D+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");D=D+"}\nreturn "+((h?"rv.then(onDone)":`onDone(${H})`)+";");let [M,Rc]=[pa,
D+"}\n"];M.push(Rc);m=dc(M)(...p);r=ac(r,m);m=b-1;if(!f.hasOwnProperty(n))throw new Sb("Replacing nonexistent public symbol");void 0!==f[n].B&&void 0!==m?f[n].B[m]=r:(f[n]=r,f[n].ha=m);return[]})},_embind_register_integer:(a,b,c,d,e)=>{b=Q(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var g=32-8*c;e=l=>l<<g>>>g}var h=b.includes("unsigned")?function(l,n){return n>>>0}:function(l,n){return n};T(a,{name:b,fromWireType:e,toWireType:h,K:8,readValueFromPointer:vc(b,c,0!==d),G:null})},_embind_register_memory_view:(a,
b,c)=>{function d(g){return new e(u.buffer,y[g+4>>2],y[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);T(a,{name:c,fromWireType:d,K:8,readValueFromPointer:d},{Ga:!0})},_embind_register_std_string:(a,b)=>{b=Q(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=y[d>>2],g=d+4;if(c)for(var h=g,l=0;l<=e;++l){var n=g+l;if(l==e||0==v[n]){h=h?F(v,h,n-h):"";if(void 0===m)var m=h;else m+=String.fromCharCode(0),m+=h;h=n+
1}}else{m=Array(e);for(l=0;l<e;++l)m[l]=String.fromCharCode(v[g+l]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new R("Cannot pass non-string to std::string");var h=c&&g?hb(e):e.length;var l=Nc(4+h+1),n=l+4;y[l>>2]=h;if(c&&g)ib(e,v,n,h+1);else if(g)for(g=0;g<h;++g){var m=e.charCodeAt(g);if(255<m)throw W(n),new R("String has UTF-16 code units that do not fit in 8 bits");
v[n+g]=m}else for(g=0;g<h;++g)v[n+g]=e[g];null!==d&&d.push(W,l);return l},K:8,readValueFromPointer:Yb,G(d){W(d)}})},_embind_register_std_wstring:(a,b,c)=>{c=Q(c);if(2===b){var d=xc;var e=yc;var g=zc;var h=l=>ua[l>>1]}else 4===b&&(d=Ac,e=Bc,g=Cc,h=l=>y[l>>2]);T(a,{name:c,fromWireType:l=>{for(var n=y[l>>2],m,r=l+4,p=0;p<=n;++p){var q=l+4+p*b;if(p==n||0==h(q))r=d(r,q-r),void 0===m?m=r:(m+=String.fromCharCode(0),m+=r),r=q+b}W(l);return m},toWireType:(l,n)=>{if("string"!=typeof n)throw new R(`Cannot pass non-string to C++ string type ${c}`);
var m=g(n),r=Nc(4+m+b);y[r>>2]=m/b;e(n,r+4,m+b);null!==l&&l.push(W,r);return r},K:8,readValueFromPointer:Yb,G(l){W(l)}})},_embind_register_void:(a,b)=>{b=Q(b);T(a,{ib:!0,name:b,K:0,fromWireType:()=>{},toWireType:()=>{}})},_emscripten_get_now_is_monotonic:()=>1,_emscripten_memcpy_js:(a,b,c)=>v.copyWithin(a,b,b+c),_emscripten_throw_longjmp:()=>{throw Infinity;},_emval_take_value:(a,b)=>{var c=Pb[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${sc(a)}`,new R(a);a=c;a=a.readValueFromPointer(b);
return Xb(a)},_localtime_js:function(a,b,c){a=new Date(1E3*Fc(a,b));x[c>>2]=a.getSeconds();x[c+4>>2]=a.getMinutes();x[c+8>>2]=a.getHours();x[c+12>>2]=a.getDate();x[c+16>>2]=a.getMonth();x[c+20>>2]=a.getFullYear()-1900;x[c+24>>2]=a.getDay();b=a.getFullYear();x[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?Ec:Dc)[a.getMonth()]+a.getDate()-1|0;x[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();x[c+32>>2]=(b!=
d&&a.getTimezoneOffset()==Math.min(d,b))|0},_mmap_js:function(a,b,c,d,e,g,h,l){e=Fc(e,g);try{if(isNaN(e))return 61;var n=P(d),m=J.N(n,a,e,b,c),r=m.R;x[h>>2]=m.ga;y[l>>2]=r;return 0}catch(p){if("undefined"==typeof J||"ErrnoError"!==p.name)throw p;return-p.o}},_munmap_js:function(a,b,c,d,e,g,h){g=Fc(g,h);try{var l=P(e);if(c&2){if(!J.isFile(l.node.mode))throw new J.g(43);if(!(d&2)){var n=v.slice(a,a+b);J.P(l,n,g,b,d)}}}catch(m){if("undefined"==typeof J||"ErrnoError"!==m.name)throw m;return-m.o}},_tzset_js:(a,
b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();y[a>>2]=60*Math.max(g,e);x[b>>2]=Number(g!=e);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(ib(a,v,c,17),ib(b,v,d,17)):(ib(a,v,d,17),ib(b,v,c,17))},emscripten_date_now:()=>Date.now(),emscripten_get_heap_max:()=>2147483648,emscripten_get_now:()=>performance.now(),emscripten_resize_heap:a=>
{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);xa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},environ_get:(a,b)=>{var c=0;Ic().forEach((d,e)=>{var g=b+c;e=y[a+4*e>>2]=g;for(g=0;g<d.length;++g)u[e++]=d.charCodeAt(g);u[e]=0;c+=d.length+1});return 0},environ_sizes_get:(a,b)=>{var c=Ic();y[a>>2]=c.length;
var d=0;c.forEach(e=>d+=e.length+1);y[b>>2]=d;return 0},exit:a=>{Ta||(f.onExit?.(a),sa=!0);ja(a,new Ra(a))},fd_close:function(a){try{var b=P(a);J.close(b);return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.o}},fd_read:function(a,b,c,d){try{a:{var e=P(a);a=b;for(var g,h=b=0;h<c;h++){var l=y[a>>2],n=y[a+4>>2];a+=8;var m=J.read(e,u,l,n,g);if(0>m){var r=-1;break a}b+=m;if(m<n)break;"undefined"!=typeof g&&(g+=m)}r=b}y[d>>2]=r;return 0}catch(p){if("undefined"==typeof J||
"ErrnoError"!==p.name)throw p;return p.o}},fd_seek:function(a,b,c,d,e){b=Fc(b,c);try{if(isNaN(b))return 61;var g=P(a);J.v(g,b,d);E=[g.position>>>0,(z=g.position,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];x[e>>2]=E[0];x[e+4>>2]=E[1];g.X&&0===b&&0===d&&(g.X=null);return 0}catch(h){if("undefined"==typeof J||"ErrnoError"!==h.name)throw h;return h.o}},fd_write:function(a,b,c,d){try{a:{var e=P(a);a=b;for(var g,h=b=0;h<c;h++){var l=y[a>>2],n=y[a+4>>
2];a+=8;var m=J.write(e,u,l,n,g);if(0>m){var r=-1;break a}b+=m;if(m<n)break;"undefined"!=typeof g&&(g+=m)}r=b}y[d>>2]=r;return 0}catch(p){if("undefined"==typeof J||"ErrnoError"!==p.name)throw p;return p.o}},invoke_i:Oc,invoke_ii:Pc,invoke_iii:Qc,invoke_iiii:Sc,invoke_iiiii:Tc,invoke_iiiiii:Uc,invoke_iiiiiiiiii:Vc,invoke_vi:Wc,invoke_vii:Xc,invoke_viidd:Yc,invoke_viii:Zc,invoke_viiii:$c,invoke_viiiii:ad,invoke_viiiiii:bd,invoke_viiiiiiiii:cd},U=function(){function a(c){U=c.exports;U=gc();ra=U.memory;
xa();mc=U.__indirect_function_table;Da.unshift(U.__wasm_call_ctors);Ka();return U}Ja();ec();var b={env:fc,wasi_snapshot_preview1:fc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){t(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ma??=La("plugin.wasm")?"plugin.wasm":f.locateFile?f.locateFile("plugin.wasm",k):k+"plugin.wasm";Qa(b,function(c){a(c.instance)}).catch(ba);return{}}(),rc=a=>(rc=U.__getTypeName)(a);f._epub_open=a=>(f._epub_open=U.epub_open)(a);
f._epub_count=()=>(f._epub_count=U.epub_count)();f._epub_bundle=()=>(f._epub_bundle=U.epub_bundle)();f._epub_format=a=>(f._epub_format=U.epub_format)(a);f.__Z10epub_imagei=(a,b)=>(f.__Z10epub_imagei=U._Z10epub_imagei)(a,b);f.__Z12rotate_imageNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi=(a,b,c)=>(f.__Z12rotate_imageNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi=U._Z12rotate_imageNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi)(a,b,c);
var Nc=a=>(Nc=U.malloc)(a),W=a=>(W=U.free)(a);f._analyse=a=>(f._analyse=U.analyse)(a);f._rotate=(a,b)=>(f._rotate=U.rotate)(a,b);f._version=()=>(f._version=U.version)();var qb=(a,b)=>(qb=U.emscripten_builtin_memalign)(a,b),Z=(a,b)=>(Z=U.setThrew)(a,b),dd=()=>(dd=U.emscripten_stack_init)(),za=()=>(za=U.emscripten_stack_get_end)(),X=a=>(X=U._emscripten_stack_restore)(a),Jc=a=>(Jc=U._emscripten_stack_alloc)(a),Y=()=>(Y=U.emscripten_stack_get_current)();
f.dynCall_ji=(a,b)=>(f.dynCall_ji=U.dynCall_ji)(a,b);f.dynCall_jiiii=(a,b,c,d,e)=>(f.dynCall_jiiii=U.dynCall_jiiii)(a,b,c,d,e);f.dynCall_viij=(a,b,c,d,e)=>(f.dynCall_viij=U.dynCall_viij)(a,b,c,d,e);f.dynCall_jiji=(a,b,c,d,e)=>(f.dynCall_jiji=U.dynCall_jiji)(a,b,c,d,e);f.dynCall_iji=(a,b,c,d)=>(f.dynCall_iji=U.dynCall_iji)(a,b,c,d);f.dynCall_jji=(a,b,c,d)=>(f.dynCall_jji=U.dynCall_jji)(a,b,c,d);f.dynCall_iiji=(a,b,c,d,e)=>(f.dynCall_iiji=U.dynCall_iiji)(a,b,c,d,e);
f.dynCall_vij=(a,b,c,d)=>(f.dynCall_vij=U.dynCall_vij)(a,b,c,d);f.dynCall_viijii=(a,b,c,d,e,g,h)=>(f.dynCall_viijii=U.dynCall_viijii)(a,b,c,d,e,g,h);f.dynCall_iiiiij=(a,b,c,d,e,g,h)=>(f.dynCall_iiiiij=U.dynCall_iiiiij)(a,b,c,d,e,g,h);f.dynCall_iiiiijj=(a,b,c,d,e,g,h,l,n)=>(f.dynCall_iiiiijj=U.dynCall_iiiiijj)(a,b,c,d,e,g,h,l,n);f.dynCall_iiiiiijj=(a,b,c,d,e,g,h,l,n,m)=>(f.dynCall_iiiiiijj=U.dynCall_iiiiiijj)(a,b,c,d,e,g,h,l,n,m);
function Wc(a,b){var c=Y();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}function Pc(a,b){var c=Y();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}function Zc(a,b,c,d){var e=Y();try{V(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Z(1,0)}}function Qc(a,b,c){var d=Y();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}function Xc(a,b,c){var d=Y();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}
function Sc(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;Z(1,0)}}function Tc(a,b,c,d,e){var g=Y();try{return V(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Z(1,0)}}function ad(a,b,c,d,e,g){var h=Y();try{V(a)(b,c,d,e,g)}catch(l){X(h);if(l!==l+0)throw l;Z(1,0)}}function Oc(a){var b=Y();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Z(1,0)}}function bd(a,b,c,d,e,g,h){var l=Y();try{V(a)(b,c,d,e,g,h)}catch(n){X(l);if(n!==n+0)throw n;Z(1,0)}}
function Vc(a,b,c,d,e,g,h,l,n,m){var r=Y();try{return V(a)(b,c,d,e,g,h,l,n,m)}catch(p){X(r);if(p!==p+0)throw p;Z(1,0)}}function Uc(a,b,c,d,e,g){var h=Y();try{return V(a)(b,c,d,e,g)}catch(l){X(h);if(l!==l+0)throw l;Z(1,0)}}function Yc(a,b,c,d,e){var g=Y();try{V(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Z(1,0)}}function $c(a,b,c,d,e){var g=Y();try{V(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;Z(1,0)}}
function cd(a,b,c,d,e,g,h,l,n,m){var r=Y();try{V(a)(b,c,d,e,g,h,l,n,m)}catch(p){X(r);if(p!==p+0)throw p;Z(1,0)}}f.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?f["_"+a]:(...g)=>Kc(a,b,c,g,d)};f.UTF8ToString=(a,b)=>a?F(v,a,b):"";f.FS=J;var ed;Ia=function fd(){ed||gd();ed||(Ia=fd)};
function gd(){function a(){if(!ed&&(ed=!0,f.calledRun=!0,!sa)){Aa();f.noFSInit||J.$||J.U();J.na=!1;Sa(Da);aa(f);f.onRuntimeInitialized?.();Aa();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ea.unshift(b)}Sa(Ea)}}if(!(0<Ga)){dd();ya();if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();Sa(Ca);0<Ga||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):
a(),Aa())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();gd();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
